### PR TITLE
[Technical-support] Prompt 5: Workflow Permissions Forms and Workflow

### PR DESCRIPTION
**Pull request by tototrinh**
Hi @holatuwol
I updated my work for Prompt 5. Please help me review and give me your comment.
Thanks

### CODE REVIEW

**Comment by holatuwol** [comment]
First, looking at the code that was changed, I don't see how the second issue (steps to reproduce as a user with view permissions) is resolved. Can you explain why the second issue is resolved?

Second, based on the documentation, a content reviewer has full permissions over tasks for assets they can review (specifically, tasks that are assigned to a role they have been granted and tasks that have been assigned specifically to their user).

https://github.com/liferay/liferay-docs/blob/master/en/user/articles/140-workflow/04-reviewing-assets.markdown#asset-submission-to-workflow

However, your changes make it so that a content reviewer has full permissions over all tasks within the site, including those that haven't been assigned to their role or that have been assigned specifically to their user.

Can you look into how to resolve the issue without elevating the permissions of the content reviewer?

**Comment by tototrinh** [comment]
Hi @holatuwol ,
Thanks for your feedback.
For the second issue, it was solved by changing the code in https://github.com/holatuwol/liferay-portal/pull/143/commits/4c4f2deacf29b60f825096642a5effd6b19bb34e. Because in the unmodified code, The permission checker checks for the Content Reviewer Role will return immediately when the user is  not a content reviewer. This will skip the permissions check related to the role that I have defined. So I changed the process to avoid that.
On the other hand, as you mentioned above, maybe I made the mistake of understanding Content Reviewer Role. For a content reviewer, **is it necessary to check if the Workflow Task can be assigned to a role or to their users?**
I will review and adjust my changes. Thanks.

**Comment by holatuwol** [comment]
> For a content reviewer, is it necessary to check if the Workflow Task can be assigned to a role or to their users?

Yes.

**Comment by tototrinh** [comment]
Hi @holatuwol ,
I updated my changes for the second issue.
As I mentioned above, The permission checker checks for the Content Reviewer Role will return immediately when the user is not a content reviewer even though the user has permission to view the content (in this case DDLRecord). Therefore, I think it would be better if I added the condition so that the Permission Checker does not return false in case the user is not Content Reviewer and has VIEW permission.
Please have a look and give me your comments. Thanks

**Comment by tototrinh** [comment]
I have a question when doing this Prompt. When I performed the debug on the checkWorkflowTaskViewPermission function I noticed that after executing the hasPermission function in WorkflowTaskPermissionChecker it will perform the permissions check related to the role. I'm actually a bit confused about when this permissions check will be performed, where it's called and how? Could you please help me explain this? Thanks

**Comment by holatuwol** [comment]
Failed source formatting.

```
ant setup-sdk
cd modules
../gradlew :apps:forms-and-workflow:portal-workflow:portal-workflow-task-web:formatSource
```

> When I performed the debug on the checkWorkflowTaskViewPermission function I noticed that after executing the hasPermission function in WorkflowTaskPermissionChecker it will perform the permissions check related to the role.

Liferay does a lot of permission checks on page render, so I would need to get on a screenshare to understand which permission check you're concerned about.

**Comment by tototrinh** [comment]
I updated my change for source format. Please have a look. Thanks.

**Comment by holatuwol** [comment]
The changes make sense to me. If you still have any questions related to permission checks, please feel free to reach out to me on Slack.

If you'd like additional context, please see [LPS-66409](https://issues.liferay.com/browse/LPS-66409).

**Pull request closed without merging**
