### PR TITLE
TSPrompt3-1: Avoid NPE in ComboServlet

### PR DESCRIPTION
**Pull request by hongvo2308**
Hi @holatuwol 
This is the PR for the Prompt 3 section 1. I hope that you could review it and give me your comments.
Thank you.

### CODE REVIEW

**Comment by holatuwol** [comment]
We see a lot of `Validator.isNull` calls for String objects, because there is a specific version of `isNull` for Strings.

https://github.com/tototrinh/liferay-portal/blob/debug-prompt-frontend-null-pointer/portal-kernel/src/com/liferay/portal/kernel/util/Validator.java#L1065-L1106

However, there isn't one for Portlet, so it will end up using Object. We know that `portlet` is neither a Long nor a String, so the extra `instanceof` checks in the `isNull` implementation are wasteful when we can check for `null` directly.

https://github.com/tototrinh/liferay-portal/blob/debug-prompt-frontend-null-pointer/portal-kernel/src/com/liferay/portal/kernel/util/Validator.java#L1040-L1053

Can you update your change to be a simpler null check?

**Comment by hongvo2308** [comment]
@holatuwol 
Thank you for your comment. I will update this.

**Comment by hongvo2308** [comment]
Hi @holatuwol 
I have updated this PR. Please be noted.
Thank you.

**Comment by holatuwol** [comment]
This looks fine to me.

Please see [LPS-73444](https://issues.liferay.com/browse/LPS-73444) for additional context.

**Pull request closed without merging**
