### PR TITLE
[TS] Prompt 3 - NullPointer Frontend: Remove Null Pointer Exception.

### PR DESCRIPTION
**Pull request by haubuicodeengine**
@holatuwol Please help me review this PR

Test script
---------------------------
1. Add a Web Content Display portlet to the homepage.
2. Reload that page.
3. Open dev tools in Chrome and go to the browser Sources tab. Copy the name of a "combo?browserId..." file which includes "JournalContentPortlet_INSTANCE_" in the name.
4. Paste that value into the browser search bar, change the portlet ID "JournalContentPortlet_INSTANCE" by misspelling it and press enter.

Result: A 404 error will appear as the URL doesn't actually exist.

I have a curious question. Why did we name that servlet "Combo" ?

Thank so much.

### CODE REVIEW

**Comment by holatuwol** [comment]
My understanding is that we named it `combo` because that's what it was called in the YUI documentation, which is what we originally used for managing modules back in 6.x.

https://yuilibrary.com/yui/docs/yui/loader.html

Performance-wise, for your solution, there isn't a specific `Validator.isNull` for portlet, so it will end up using the one Object.

https://github.com/tototrinh/liferay-portal/blob/debug-prompt-frontend-null-pointer/portal-kernel/src/com/liferay/portal/kernel/util/Validator.java#L1040-L1053

We know that `portlet` is neither a Long nor a String, so the extra `instanceof` checks in the `isNull` implementation are wasteful when we can check for `null` directly.

Can you update your change to be a simpler null check?

**Comment by haubuicodeengine** [comment]
I updated the PR. Please help me take a look.
@holatuwol Thank you for your explanation.

**Comment by holatuwol** [comment]
Failed source formatting.

```
ant setup-sdk
cd portal-impl
ant format-source-current-branch -Dgit.working.branch.name=a182d3177c97b0e5705c5d23b0aa49c7e586c358
```

**Comment by haubuicodeengine** [comment]
@holatuwol I updated this PR. Please help me review it.
Thanks.

**Comment by holatuwol** [comment]
Everything looks okay.

If you'd like to know more about the original bug report, please review [LPS-73444](https://issues.liferay.com/browse/LPS-73444).

**Pull request closed without merging**
