### PR TITLE
LPS-136280 Update pattern so images are rendered as picture tags

### PR DESCRIPTION
**Pull request by tototrinh**
@holatuwol, in https://issues.liferay.com/browse/LPP-42161, I noticed that when an image has an alt attribute (this is the default when adding an Image on WC) or some other attribute, the image won't be able to display as an image tag.
https://github.com/liferay/liferay-portal-ee/blob/master/modules/apps/adaptive-media/adaptive-media-content-transformer-api/src/main/java/com/liferay/adaptive/media/content/transformer/BaseRegexStringContentTransformer.java#L40-L56
https://github.com/liferay/liferay-portal-ee/blob/7.3.x/modules/apps/adaptive-media/adaptive-media-image-content-transformer-backwards-compatibility/src/main/java/com/liferay/adaptive/media/image/content/transformer/backwards/compatibility/internal/AMBackwardsCompatibilityHtmlContentTransformer.java#L105-L107
so I updated the pattern. Please help me review this PR and give me your feedback. Thanks.

### CODE REVIEW

**Comment by holatuwol** [comment]
I don't think we need any capturing groups for the new pattern. This should work just as well:

```java
Pattern pattern = Pattern.compile(
    "<img\\s+[^>]*src=['\"]/documents/(\\d+)/(\\d+)/([^/?]+)" +
        "(?:/([-0-9a-fA-F]+))?(?:\\?t=\\d+)?['\"][^>]*/>");
```

**Comment by tototrinh** [comment]
Thanks for your feedback. 
I tried with your suggestion and when I publish WC with the source like below:
```
<p><br />
<img alt="" gfsrc="/documents/20125/40202/adorable-cat.jpg/f8976630-fea5-00ba-6ac8-d648d94d030e?t=1627524815320" /><br />
 </p>
```
I found that the image won't be displayed when previewing. However, the Image will be displayed if I do inspect (F12). Is this acceptable?

**Comment by holatuwol** [comment]
Ah, let's try a non-capturing group then.

```java
Pattern pattern = Pattern.compile(
    "<img\\s+(?:[^>]*\\s)*src=['\"]/documents/(\\d+)/(\\d+)/([^/?]+)" +
        "(?:/([-0-9a-fA-F]+))?(?:\\?t=\\d+)?['\"][^>]*/>");
```

**Comment by tototrinh** [comment]
Thank you for your help. I have updated the PR post. Please take a look again.

**Comment by tototrinh** [comment]
I noticed that changing the pattern caused the issue as mentioned at [LPS-79815](https://issues.liferay.com/browse/LPS-79815). So I added a commit to fix it.

**Comment by holatuwol** [comment]
https://github.com/liferay-lima/liferay-portal/pull/2109

**Pull request closed without merging**
