### PR TITLE
LPS-106390 Add command to be able to execute scripts that import classes from modules.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
Hi @holatuwol,
 do you think we can include this command in the product. Several customers have asked us for this functionality, since infrastructure admins do not always have a Liferay admin user to access control panel.
Kind regards.

**Comment by holatuwol** [comment]
@marianoalvarosaiz : Don't we disable GoGo shell via telnet by default for security reasons? I don't think that infrastructure admins would re-enable it, knowing the risks.

**Comment by marianoalvarosaiz** [comment]
Hi @holatuwol,
 you're right, but since we allow to enable it and some customers have demanded it, I think that we should fix it, giving the possibility to execute an script importing module classes to those customers that want to do so.
Kind regards.

**Comment by holatuwol** [comment]
@marianoalvarosaiz : Can you add it to the Groovy scripting module which only uses the Groovy scripting executor and make the command `groovy`? GoGo shell has its own scripting language (`gosh`), so just having a generic-sounding one to run Groovy scripts doesn't make sense.

**Comment by marianoalvarosaiz** [comment]
Hi @holatuwol,

 it looks specific to Groovy because right now the only ScriptingExecutor that we have is GroovyExecutor, but I used a generic location because it's using ScriptingImpl that receives, in the eval method, the language. To make it more clear I've added an additional command that shows all currently available scripting languages (see new commit).

Kind regards.

**Comment by holatuwol** [comment]
@marianoalvarosaiz : Looking into it some more, all of the capabilities of this script are technically already available through the Gogo shell. I don't feel confident forwarding this as a way to simplify something most people disable.

Can you look through the comment I left on [LPS-106390](https://issues.liferay.com/browse/LPS-106390) and see if it satisfies your needs? Or would you prefer that I forward this anyway, even though a known alternative exists?

**Comment by marianoalvarosaiz** [comment]
@holatuwol: Firstly, thanks a lot. 

Regarding the solution, I've some doubts. Indeed your solution makes it technically possible, but I don't know how would it look to document it, using a "web" module to execute "backend" scripts, and how intuitive would it look.

Honestly it saves making a solution and it would satisfy customer needs. I'm not fully convinced in "magically" coupling the code to the server admin module, but probably is better than making a new Gogo command.

**Comment by holatuwol** [comment]
*I'm not fully convinced in "magically" coupling the code to the server admin module, but probably is better than making a new Gogo command.*

@marianoalvarosaiz : Yeah, to me, they're both magical hacks, since ultimately, what makes them work is equivalent to how we resolved [LPS-70234](https://issues.liferay.com/browse/LPS-70234): switch the thread context classloader to a bundle classloader for a bundle that has `Dynamic-ImportPackage: *` set, so that the logic inside of `BaseScriptingExecutor` returns a classloader that can dynamically load any and all missing classes.

Another solution is to update the LPS-70234 solution to make it reusable, and then update both `server-admin-web` and `portal-workflow-kaleo-runtime-scripting-impl` to use it (hopefully allowing us to remove the `DynamicImport-Package: *` manifest instruction from both), which would simplify the gosh script as well. However, I don't know whether it's worthwhile since my understanding is that we want to avoid `DynamicImport-Package` in OSGi as much as possible.

**Comment by marianoalvarosaiz** [comment]
> Another solution is to update the LPS-70234 solution to make it reusable

@holatuwol: you mean something like this https://github.com/holatuwol/liferay-portal/pull/108?

With this solution we could easily adapt the product part of https://github.com/holatuwol/liferay-portal/pull/107 so that the jar uses the _DynamicClassLoader_ (I haven't create a constant to kind of discourage its use). I've seen that there are several others marketplace apps that are making use of _DynamicImport_ and could also be adapted.

**Comment by holatuwol** [comment]
@marianoalvarosaiz : Something similar, but I think we specifically avoid allowing all scripts to be forced to use dynamic imports, because of the known problems in libraries like log4j.

**Pull request closed without merging**
