### PR TITLE
Debug prompt wcm dm pagination

### PR DESCRIPTION
**Pull request by dhavaldesai75**
Hi @holatuwol,
I have made the code changes for the debug-prompt-wcm-dm-pagination. Please review it and provide feedback.
Thanks,
Dhaval

### CODE REVIEW

**Comment by holatuwol** [comment]
@dhavaldesai75 Can you remove the comments and the blank lines?

Also, in `init.jsp`, I see an unused variable `folderperPage`. Was this intentional?

**Comment by dhavaldesai75** [comment]
Hi @holatuwol ,

I have removed the comments and the blank lines.
In the init.jsp, I have removed the folderPage variable. I don't need it.

Thanks,
Dhaval

**Comment by holatuwol** [comment]
It's a bit nit-picky, but can you rename the variable to `entriesPerPage` (since it's three words, camel cased) and exclude the `.gitignore` changes?

**Comment by dhavaldesai75** [comment]
entriesPerPage  variable is made camel cased now. Removed the files added to .gitignore..

Thanks

**Comment by holatuwol** [comment]
Everything looks fine to me!

If you'd like to review the original bug ticket, please see [LPS-67332](https://issues.liferay.com/browse/LPS-67332).

**Pull request closed without merging**
