### PR TITLE
LPS-142767 Change skipEditorLoading to false

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
https://issues.liferay.com/browse/LPS-142767

When leaving a comment in Workflow task and then doing any of the tasks, assign to me, assign to, or  Update Due Date, the page will load with an error stating the CKEditor is not defined. I found that the URL contains `_skipEditorLoading=true` which is preventing CKEditor from loading.

I was able to change this variable to false and the page now loads the CKEditor correctly.
I tried testing other forms of this with wiki and message boards and I do not see a change. Let me know if this would be the best way to go about fixing this issue or if I should try something else.

Thank you!

### CODE REVIEW

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by holatuwol** [comment]
Forcing skipEditorLoading to true was added in order to resolve [LPS-81691](https://issues.liferay.com/browse/LPS-81691). Do you know if the issue comes back after these changes?

**Comment by fortunatomaldonado** [comment]
Hello @holatuwol,
I check this behavior and do not believe these changes are being reverted.

**Comment by holatuwol** [comment]
If the change doesn't introduce any regressions, then I think the change makes sense as a way to resolve the issue. Did you want me to forward the pull request?

**Comment by fortunatomaldonado** [comment]
Okay sounds good. If it is not too much trouble to forward, otherwise I can forward it.
Thank you for taking a look at this!

**Comment by holatuwol** [comment]
https://github.com/liferay-frontend/liferay-portal/pull/1762

**Pull request closed without merging**
