### PR TITLE
[TS] LPS-138379 portal-web: Append namespace to remove the proper parameter

### PR DESCRIPTION
**Pull request by ericyanLr**
Hey @holatuwol ,

https://issues.liferay.com/browse/LPS-138379

This fix is related to a fix you worked on: [Scrolling does not work in intermediate pages of the page-iterator tag library](https://issues.liferay.com/browse/LPS-131653)

Just wanted to run this by you, in case there's anything I overlooked.

Can you help take a look?
Thanks!

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by holatuwol** [comment]
I believe I was imitating `_getHREF`:

https://github.com/holatuwol/liferay-portal/blob/070b78c5fa3cc0fbc6ddfef63ad1b277ea1ea57c/portal-web/docroot/html/taglib/ui/page_iterator/lexicon/start.jsp#L379-L385

However, I see now that all the invocations of `_getHREF` are passing along the namespace.

**Comment by holatuwol** [comment]
https://github.com/liferay-frontend/liferay-portal/pull/1420

**Pull request closed without merging**
