### PR TITLE
[TS] LPS-148438 - Use same ownerid to add preferences on process portlet method

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
For steps, please check https://issues.liferay.com/browse/LPS-148438

### CODE REVIEW

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by holatuwol** [comment]
https://github.com/liferay-core-infra/liferay-portal/pull/405

**Comment by tinatian** [comment]
@holatuwol Code looks good to me. I will trigger ci:test to confirm no side effect caused by this, once QA scanned the test results, it should be good to go.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
ci:stop

**Pull request closed without merging**
