### PR TITLE
LPS-116291: Remove portlet resource param in redirect url

### PR DESCRIPTION
**Pull request by haubuicodeengine**
https://issues.liferay.com/browse/LPS-116291

This problem occurs in all options in the "Add" pane.
I remove the portlet resource parameter in the redirect url. So after adding new content, it will be redirected to the original url.

Example: The new redirect url is 
http://localhost:8080/web/guest/wp
instead of 
http://localhost:8080/web/guest/wp?portletResource=com_liferay_product_navigation_control_menu_web_portlet_ProductNavigationControlMenuPortlet&_com_liferay_product_navigation_control_menu_web_portlet_ProductNavigationControlMenuPortlet_className=com.liferay.journal.model.JournalArticle&_com_liferay_product_navigation_control_menu_web_portlet_ProductNavigationControlMenuPortlet_classPK=38405

Please help me to review it. Thank you.

### CODE REVIEW

**Comment by holatuwol** [comment]
Looking at the commit which made it `portletResource` (https://github.com/holatuwol/liferay-portal/commit/1ba61e940c24110a2b53eb8613c5b4f0ecd6aec8), rather than completely removing that line, can you check to see what happens if we use `p_p_id` instead of `portletResource` to see if it resolves the issue?

**Comment by haubuicodeengine** [comment]
Following your suggestion, I use `p_p_id` instead of `portletResource` and change on all portlets related to all options when adding new content. You can see the commit.

I tested adding new content with all the options, and it was fine.

Example: The new redirect url is 
http://localhost:8080/web/guest/wp?p_p_id=com_liferay_product_navigation_control_menu_web_portlet_ProductNavigationControlMenuPortlet&__className=com.liferay.document.library.kernel.model.DLFileEntry&__classPK=38711
Instead of
http://localhost:8080/web/guest/wp?portletResource=com_liferay_product_navigation_control_menu_web_portlet_ProductNavigationControlMenuPortlet&__className=com.liferay.document.library.kernel.model.DLFileEntry&__classPK=38711

In my opinion, if we change with this, It is very unsafe. Because we don't know if it will break other features or not.
And the `p_p_id` parameter is used in many places, maybe it will be collision with other parameters.
Example: image

**Comment by holatuwol** [comment]
Sorry for not clarifying. I wanted you to test updating `product-navigation-control-menu-web/src/main/resources/META-INF/resources/view_resources.jsp`. In your original commit, you deleted this line. I wanted to see if we changed it to `p_p_id`, in just this one place.

```
redirectURL = HttpUtil.addParameter(redirectURL, "portletResource", portletDisplay.getId());
```

**Comment by haubuicodeengine** [comment]
When we just change `portletResource` to `p_p_id` in `view_resource.jsp,` the redirect url will be
http://localhost:8080/web/guest/wp?p_p_id=com_liferay_product_navigation_control_menu_web_portlet_ProductNavigationControlMenuPortlet

The problem will be solved. I think that is the same way when we remove this line
`redirectURL = HttpUtil.addParameter(redirectURL, "portletResource", portletDisplay.getId()); `

It does not add the `className` and` classPK` parameters to the url because the value of `portletResource` is null.
```
String portletResource = _http.getParameter(redirect, "portletResource", false);

if (Validator.isNotNull(portletResource)) {
        redirect = _http.addParameter(
                redirect, namespace + "className",
                .....
}
```

**Comment by holatuwol** [comment]
Got it. Can you go back to your original solution of removing the line then? It sounds like you're more comfortable with that solution, and since it doesn't make a difference, we'll move forward with that.

**Comment by haubuicodeengine** [comment]
I have updated the commitment with my original solution. Please help me to review it.
Sorry for delay the commitment to the end of the day. I had a little more time to think about it.

**Comment by holatuwol** [comment]
https://github.com/dacousalr/liferay-portal/pull/254

**Pull request closed without merging**
