### PR TITLE
LPS-83543

### PR DESCRIPTION
**Pull request by ChrisKian**
See https://github.com/jonathanmccann/liferay-portal/pull/1665

https://issues.liferay.com/browse/LPS-83543
https://issues.liferay.com/browse/LPP-30862

Resending because of test failures due to not properly adding the folder (instead running the create and update methods).

Let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by holatuwol** [comment]
Making sure I understand. Why `folder.getCompanyId()` and `folder.getFolderId()` instead of `importedFolder.getCompanyId()` and `importedFolder.getFolderId()`?

**Comment by ChrisKian** [comment]
You mean for the fetch right?  I'm trying to fetch the workflow of the existing folder (before staging is involved).  If I find it, I want it essentially duplicated for the newly created staging folder.

When staging is enabled, "folder" becomes the live folder, and "importedFolder" becomes the staged folder.  If we have a workflow on the live folder, it doesn't do anything, since only published content can make it to the live site.

**Comment by ChrisKian** [comment]
Hey @holatuwol,

I tested with remote staging and everything works as expected; once staging has been enabled, the staging folder still has it's workflow.  This is true whether the folder already had workflow enabled before staging was enabled or not.

Let me know fi you have any questions.  Thanks!

**Comment by holatuwol** [comment]
https://github.com/matethurzo/liferay-portal/pull/2206

**Pull request closed without merging**
