### PR TITLE
[TS] Prompt 2 Web Content Tags

### PR DESCRIPTION
**Pull request by dinh-thai**
Hi @holatuwol,
I have finish session 3 of Prompt 2.
Please help me take a look.
Thankyou

### CODE REVIEW

**Comment by holatuwol** [comment]
Failed source formatter.

```
ant setup-sdk compile
cd portal-impl
ant format-source-current-branch -Dgit.working.branch.name=d36c61d91e62df18521194694c31538aca299b17
```

**Comment by dinh-thai** [comment]
> Failed source formatter.
> 
> ```
> ant setup-sdk compile
> cd portal-impl
> ant format-source-current-branch -Dgit.working.branch.name=d36c61d91e62df18521194694c31538aca299b17
> ```

Hi @holatuwol

I have update and run source formatter again.
Please help me take a look.

Thank you

**Comment by holatuwol** [comment]
Can you provide a comment describing what you learned while troubleshooting this issue?

**Comment by dinh-thai** [comment]
> Can you provide a comment describing what you learned while troubleshooting this issue?

After I reproduce this issue, I use Eclipse IDE for debug.
During debug, I see that the first time publish Basic web content, the tags name is be convert to lowercase before save (com.liferay.portlet.asset.service.impl.AssetTagLocalServiceImpl.addTag(long, long, String, ServiceContext))

At the second time publish Basic web content, at method `com.liferay.portlet.asset.service.impl.AssetTagLocalServiceImpl.checkTags(long, Group, String[])`, it loop tags name and send it as param to method `com.liferay.portlet.asset.service.impl.AssetTagLocalServiceImpl.fetchTag(long, String)`, then is `com.liferay.portlet.asset.service.persistence.impl.AssetTagPersistenceImpl.fetchByG_N(long,`` String, boolean)` but missing convert to lowercase. 
So the result of query from AssetTag table return null.

At method `com.liferay.portlet.asset.service.impl.AssetTagLocalServiceImpl.checkTags(long, Group, String[])`, when result of query from AssetTag table return null, it will add new tag name. But in method `com.liferay.portlet.asset.service.impl.AssetTagLocalServiceImpl.addTag(long, long, String, ServiceContext)`, it has check again using method `com.liferay.portlet.asset.service.impl.AssetTagLocalServiceImpl.hasTag(long, String)`, in this line, name is converted to lowercase before check, and because this tag name is already exist in DB so it will throw new DuplicateTagException.

The solution is before go to method `com.liferay.portlet.asset.service.impl.AssetTagLocalServiceImpl.fetchTag(long, String)`, tag name must be converted to lowercase.

And I have check again about working branch name.
I run source format again:
```
ant setup-sdk compile
cd portal-impl
ant format-source-current-branch -Dgit.working.branch.name=bb2ea556b908e2abdcb81c454bf2f7e85b63c27a
```

Please help me take a look.
Thank you!

**Comment by holatuwol** [comment]
Sounds good. For additional context, please see [LPS-74630](https://issues.liferay.com/browse/LPS-74630)

**Pull request closed without merging**
