### PR TITLE
Prompt2 - LowerCase before fetch tag

### PR DESCRIPTION
**Pull request by huynguyen-codeengine**

### CODE REVIEW

**Comment by holatuwol** [comment]
Failed source formatter.

```
ant setup-sdk compile
cd portal-impl
ant format-source-current-branch -Dgit.working.branch.name=d36c61d91e62df18521194694c31538aca299b17
```

**Comment by huynguyen-codeengine** [comment]
Source formatted.

**Comment by huynguyen-codeengine** [comment]
Source formatted.

**Comment by holatuwol** [comment]
Can you explain what you learned as you were troubleshooting this prompt?

**Comment by huynguyen-codeengine** [comment]
I have learned as were troubleshooting this prompt
  - Read the log file of Tomcat server to see what really happen behind the simple error message on the screen.
  - Liferay tag is not case sensitive
  - How to setup the remote debug for IntelliJ and Eclipse .
  - Format source before commit.

**Comment by holatuwol** [comment]
Makes sense to me. For additional context, please see [LPS-74630](https://issues.liferay.com/browse/LPS-74630).

**Pull request closed without merging**
