### PR TITLE
LPS-119542 Disable article ellipses menu when toggle

### PR DESCRIPTION
**Pull request by huynguyen-codeengine**
From @hongvo2308
I added one class for the menu. I also checked if this class cause unexpected Style.
Please review this PR and leave your comments.
Thank you.

### CODE REVIEW

**Comment by holatuwol** [comment]
@hongvo2308 : Why are we adding a new rule to the .css file? Does adding `lfr-configurator-visibility` cause an undesirable side-effect?

**Comment by hongvo2308** [comment]
Hi @holatuwol 
I try to follow the style of the class ".portlet-topper-toolbar" cause I found it it the ellipsis portlet menu. But this class has some margin options so I decided to create a new class. I have take a look at the .lfr-configurator-visibility class yet. I will take a look at it.
Thank you.

**Comment by hongvo2308** [comment]
Hi @holatuwol 
The ".lfr-configurator-visibility" class has opacity property so I will affect to the current style of the ellipsis menu. And I found that the current style of the ellipsis menu has margin, so when we use the "display: none" property, it cause some transitions. 
How do you think about this? Shall we use "visibility: hidden" instead or add "margin: 0px" to this component?
Thank you.

**Comment by holatuwol** [comment]
`visibility: hidden` makes more sense.

**Comment by huynguyen-codeengine** [comment]
Forward changes from @hongvo2308.

**Comment by holatuwol** [comment]
Alternate fix.

https://github.com/hongvo2308/liferay-portal/pull/3

**Pull request closed without merging**
