### PR TITLE
LPS-120920 Validate and update Live Site DLReference from Staging

### PR DESCRIPTION
**Pull request by dinh-thai**
From @hongvo2308

> The issue is https://issues.liferay.com/browse/LPP-38837
> I found that there was image created for the live site corresponding with the staging site. So I decide to make a validate and replace repository groupId when updating live site.
> 
> Update: You can find the replicating file process at https://github.com/holatuwol/liferay-portal/blob/b912d2547bd90f98d2fb7d14d9354ad70d074e46/modules/apps/document-library/document-library-service/src/main/java/com/liferay/document/library/internal/exportimport/data/handler/FileEntryStagedModelDataHandler.java#L507

Issue
A section's background image is not published to Live site when using Content Pages with Staging

Steps to Reproduce

1. Enable Staging on the target site
2. Check the Group ID of the site in Site Settings, and make note of it (e.g. 34378)
3. Add a new public page with Content Page type
4. Edit the Content Page
5. On the right hand panel, select Section Builder (the second icon)
6. Click the Layouts dropdown, and drag the first (1 column) layout onto the page
7. Click on the newly added section and click on the Layout Background Image icon (the second contextual icon)
8. Click the Select button, and select an image file to add as the background. Once completed, click Add.
9. Inspect that Section, and make note of the URL and groupId (e.g. 37061):
`box-sizing: border-box;background-position: 50% 50%; background-repeat: no-repeat; background-size: cover; background-image: url(/documents/37061/0/sample.png/e30dcdfb-87f2-dcc0-b5e1-8b82bd6be46a?t=1600062453164&download=true);border-style: solid; border-width: 0px;opacity: 1.0;
`
10. Publish the Content Page
11. Revisit the Content Page, then Publish the page from Staging to Live
12. Check the Live version of that page, and inspect the Section, and make note of the URL and groupId:
`box-sizing: border-box;background-position: 50% 50%; background-repeat: no-repeat; background-size: cover; background-image: url(/documents/37061/0/sample.png/e30dcdfb-87f2-dcc0-b5e1-8b82bd6be46a?t=1600062453164&download=true);border-style: solid; border-width: 0px;opacity: 1.0;`

HI @holatuwol ,
This is pass my review.
Please help me review it.
Thank you!

### CODE REVIEW

**Comment by holatuwol** [comment]
@hongvo2308 , @dinh-thai :

Is there a reason you're manually replacing the strings instead of calling `replaceExportContentReferences` (on export) and `replaceImportContentReferences` (on import)?

Those methods should be available on the `ExportImportContentProcessor` reference that you pulled in.

**Comment by hongvo2308** [comment]
Hi @holatuwol 
I have tried to use the ExportImportContentProcessor.replaceExportContentReferences, but the line
https://github.com/liferay/liferay-portal/blob/8cf7978e07383ce3f32712d7d8d2d8d73a9bac28/modules/apps/export-import/export-import-service/src/main/java/com/liferay/exportimport/internal/exportimport/content/processor/DLReferencesExportImportContentProcessor.java#L378 throws exception.
The ExportImportContentProcessor.replaceImportContentReferences does not focus on the pattern we need.
I am investigating the reason why it throws the exception

**Comment by holatuwol** [comment]
What if you pass `false` for the `exportReferencedContent` parameter?

**Comment by hongvo2308** [comment]
@holatuwol 
I set it false and it still gets to throwing the exception

**Comment by holatuwol** [comment]
That's weird. The exception is in an if-block that checks whether it's true? Is the stack trace slightly different?

**Comment by hongvo2308** [comment]
Both of the cases will execute the PortletDataContextImpl.getExportDataGroupElement(String name). And for the both cases, the _exportDataRootElement is null. So it throws exception.

**Comment by holatuwol** [comment]
Hm, I just tested the changes and didn't see any exceptions.

https://github.com/hongvo2308/liferay-portal/pull/7

Can you verify?

**Pull request closed without merging**
