### PR TITLE
LPP-37487: Avoid /web/site-friendly-url being stripped when accessing portal instance's virtual host

### PR DESCRIPTION
**Pull request by tototrinh**
Hi Minh Chau,
I updated my work for this ticket. 
With my change, when accessing by portal instance's virtual host **/web/site-friendly-url**  will not be stripped.
Please help me to review and give me your feedback.
Thanks

### CODE REVIEW

**Comment by tototrinh** [comment]
Hi Minh Chau
I updated my work. Please have a look and give me your feedback.
Thanks

**Comment by holatuwol** [comment]
It looks like your comments are in the wrong order (first comment is for the second code block, second comment is for the first code block). However, usually we remove comments in Liferay, so can you go ahead and remove the comment and instead add it as a commit message?

Next, based on the current code flow, you can also simplify the code a bit like this:

```java
if (isPortalInstanceVirtualHost) {
	if (virtualHostnames.containsKey(portalInstanceVirtualHostName)) {
		return true;
	}
	return false;
}
```

However, that raises the question: if a virtual host is set on the company, is it possible to set the site's public virtual host to the same value? That seems to be the only condition where `virtualHostnames.containsKey(portalInstanceVirtualHostName)` will return true, and my understanding is that it's currently a unique index.

https://github.com/liferay/liferay-portal/blob/7.3.2-ga3/portal-impl/src/com/liferay/portal/service.xml#L3186-L3188

Would you be able to double-check?

**Comment by tototrinh** [comment]
Thanks for your feedback. I got VirtualHost by this function
https://github.com/liferay/liferay-portal/blob/7.3.2-ga3/portal-impl/src/com/liferay/portal/util/PortalImpl.java#L5909-L5927. It will return the company virtual host when the site's public virtual host is not set. So I checked virtualHostnames.containsKey(portalInstanceVirtualHostName as a condition to check if the site's public virtual host is set?

**Comment by tototrinh** [comment]
I also updated my work. Please help me review it again. Thanks

**Comment by holatuwol** [comment]
Thanks for the clarification.

Can you create an LPS and update the commit message?

**Comment by tototrinh** [comment]
Of course, I will create the LPS ticket now. Do I need to change my commit message to make it clearer?

**Comment by holatuwol** [comment]
The text of the commit message looks fine. Just need to update it to point to the LPS you create.

**Comment by tototrinh** [comment]
Got it. Thanks

**Comment by holatuwol** [comment]
Also, as one last sanity check, since it's being returned for any site, as long as it has no explicit virtual host, can you double-check to make sure that it doesn't cause any regressions when there is a second site?

**Comment by tototrinh** [comment]
I updated commit message and also created LPS ticket: https://issues.liferay.com/browse/LPS-114577
Thanks

**Comment by holatuwol** [comment]
I've been looking at the code you linked earlier and its implications:

https://github.com/liferay/liferay-portal/blob/7.3.2-ga3/portal-impl/src/com/liferay/portal/util/PortalImpl.java#L5909-L5927

Since `layoutSet.getCompanyFallbackVirtualHostname()` will already check for `virtual.hosts.default.site.name`, that means that there shouldn't be an instance where `_containsHostname` returns false, but we want the `virtual.hosts.default.site.name` check to pass.

Can you test something simpler, where the only thing we do is remove these two lines?

https://github.com/liferay/liferay-portal/blob/7.3.2-ga3/portal-impl/src/com/liferay/portal/util/PortalImpl.java#L8378-L8379

**Comment by holatuwol** [comment]
https://github.com/dacousalr/liferay-portal/pull/232

**Pull request closed without merging**
