### PR TITLE
[TS Prompt] WCM DM Folder Name

### PR DESCRIPTION
**Pull request by mauricesepe**
Lessons Learned:
1. Setup intelliJ workspace.
2. Familiarize myself with Liferay's source code.
3. Debug JSP

### CODE REVIEW

**Comment by holatuwol** [comment]
I see a similar code pattern in vertical-card.

https://github.com/holatuwol/liferay-portal/blob/debug-prompt-wcm-dm-folder-name/modules/apps/foundation/frontend-taglib/frontend-taglib/src/main/resources/META-INF/resources/card/vertical_card/end.jspf#L26-L32

Would you happen to know whether vertical-card is similarly affected? If not, can you identify the differences?

**Comment by mauricesepe** [comment]
Upon further investigation, it looks like the error is more on the Portlet side.

vertical-card: not escaped
horizontal-card: escaped

Since the string is already escaped inside the portlet side and then escaped again on the foundation side, the issue occurs. 
I removed all HtmlUtil.escape calls for horizontal-card inside the DL Portlet.

**Comment by holatuwol** [comment]
Can you check if there any other portlets that use `liferay-frontend:horizontal-card` that are affected by a similar issue? This will return a list of some of the ones that use the tag library:

```
git ls-files modules/apps/ | tr '\n' '\0' | xargs -0 grep -Fl '<liferay-frontend:horizontal-card'
```

**Comment by mauricesepe** [comment]
Fixed other modules that may have been affected. Can you please confirm?

**Comment by holatuwol** [comment]
Were you able to reproduce the issue in the other modules before fixing them?

**Comment by mauricesepe** [comment]
Here are some update with regards my investigation:

**Able to reproduce and confirm fixes:**
1. modules/apps/collaboration/document-library/document-library-web/src/main/resources/META-INF/resources/document_library/view_entries.jsp
2. modules/apps/collaboration/document-library/document-library-web/src/main/resources/META-INF/resources/image_gallery_display/view_images.jsp
3. modules/apps/collaboration/wiki/wiki-web/src/main/resources/META-INF/resources/wiki/view.jsp
4. modules/apps/web-experience/trash/trash-web/src/main/resources/META-INF/resources/view_content.jsp

**Able to reproduce (string is hard coded since input validation does not allow for special characters) and confirm fixes:**
1. modules/apps/collaboration/item-selector/item-selector-taglib/src/main/resources/META-INF/resources/group_selector/page.jsp
2. modules/apps/web-experience/journal/journal-web/src/main/resources/META-INF/resources/view_entries.jsp

**Unable to reproduce:**
1. modules/apps/knowledge-base/knowledge-base-web/src/main/resources/META-INF/resources/admin/common/article_attachments.jsp _(can't install knowledge-base app)_
2. modules/apps/collaboration/item-selector/item-selector-taglib/src/main/resources/META-INF/resources/repository_entry_browser/page.jsp _(can't setup a repository for Documents & Media portlet)_

**Comment by holatuwol** [comment]
That's good enough for me. For additional context, please see [LPS-70409](https://issues.liferay.com/browse/LPS-70409).

**Pull request closed without merging**
