### PR TITLE
Ts prompt5

### PR DESCRIPTION
**Pull request by hongvo2308**
Hi @holatuwol 
This is the PR for the Prompt 5. I hope that you could review it and leave your comments.
Thank you.

### CODE REVIEW

**Comment by holatuwol** [comment]
First, looking at the code that was changed, I don't see how the second issue (steps to reproduce as a user with view permissions) is resolved, but I might be missing something. Can you explain why the second issue is resolved?

Second, based on the documentation, a content reviewer has full permissions over tasks for assets they can review (specifically, tasks that are assigned to a role they have been granted and tasks that have been assigned specifically to their user).

https://github.com/liferay/liferay-docs/blob/master/en/user/articles/140-workflow/04-reviewing-assets.markdown#asset-submission-to-workflow

However, your changes make it so that a content reviewer has full permissions over all tasks within the site, including those that haven't been assigned to their role or that have been assigned specifically to their user.

Can you look into how to resolve the issue without elevating the permissions of the content reviewer?

**Comment by hongvo2308** [comment]
> First, looking at the code that was changed, I don't see how the second issue (steps to reproduce as a user with view permissions) is resolved, but I might be missing something. Can you explain why the second issue is resolved?
> 
> Second, based on the documentation, a content reviewer has full permissions over tasks for assets they can review (specifically, tasks that are assigned to a role they have been granted and tasks that have been assigned specifically to their user).
> 
> https://github.com/liferay/liferay-docs/blob/master/en/user/articles/140-workflow/04-reviewing-assets.markdown#asset-submission-to-workflow
> 
> However, your changes make it so that a content reviewer has full permissions over all tasks within the site, including those that haven't been assigned to their role or that have been assigned specifically to their user.
> 
> Can you look into how to resolve the issue without elevating the permissions of the content reviewer?

The second issue is solved by these lines:
https://github.com/holatuwol/liferay-portal/pull/142/files#diff-917d08030c84204fe4f1807ce16b661aL39-L43
Because The permission checker checks for the ContentReviewer Role. If it is false then it returns immediately. This will skip the permission checking below, which is related to the Role that we have defined. Therefore, I change the process a little bit. So now it will return if it is true. If it is false, then it should check the below conditions.

**Comment by hongvo2308** [comment]
Hi @holatuwol 
I have updated this PR. I decided to add a method for checking permission View Action. Please be noted.
Thank you.

**Comment by holatuwol** [comment]
> I have updated this PR. I decided to add a method for checking permission View Action. Please be noted.

Hm, it looks like you're ignoring asset-specific permission check implementations and are focusing only on whether roles have permission to view the individual asset.

Some asset types (such as documents) require that the user also have permission to view the folder in addition to the specific asset, and therefore a role check is incorrect.

Can you look into how something that more generically checks permissions across multiple asset types (such as asset publisher) implements it and imitate the logic from there?

**Comment by hongvo2308** [comment]
Hi @holatuwol 
I have updated this PR to use the AssterEntryPermission Checking. Please review it again and leave your comments.
Thank you.

**Comment by holatuwol** [comment]
The `hasRolePermission` that you added is no longer used, so in a normal pull request, you'd squash the commits and then remove that extraneous method. However, it passes source formatter's checks, so it's likely that a reviewer would remove it afterwards.

Other than that, everything looks fine to me. If you'd like additional context, please see [LPS-66409](https://issues.liferay.com/browse/LPS-66409).

**Pull request closed without merging**
