### PR TITLE
LPS-151510 Images in HEIC format cannot be previewed in Documents and Media

### PR DESCRIPTION
**Pull request by ericyanLr**
Hi @holatuwol ,

Ticket: https://issues.liferay.com/browse/LPS-151510

As discussed, this PR adds support for HEIC images to generate previews/thumbnails for Adaptive Media when ImageMagick (with HEIC support) is setup and enabled.

Can you help review this PR? 
Please see [LPP-44743](https://issues.liferay.com/browse/LPP-44743) for additional notes.

Thanks!

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
Hi @holatuwol ,

Looking at the test results, my current implementation would result in a major version bump. I'll take another look or if you have any suggestions to avoid this, that would be great.

**Comment by ericyanLr** [comment]
**Quick Update**
Added an alternative approach: https://github.com/holatuwol/liferay-portal/pull/259

**Comment by holatuwol** [comment]
A major version bump would mean we can't backport it. We could hack around it by making the AMImageScaledImage interface a ProviderType, but we'll explore the other solution first, and revisit this one if the product team ends up wanting to update the interface.

**Comment by holatuwol** [comment]
https://github.com/liferay-lima/liferay-portal/pull/2977

**Pull request closed without merging**
