### PR TITLE
TS-Promt2: Fix the Title not to be escaped

### PR DESCRIPTION
**Pull request by hongvo2308**
Hi @holatuwol 
This PR is for the Promt 2: debug-prompt-wcm-dm-folder-name.
I have made the fix for the Folder name to be escaped. Please review it and give me your comments.
Thank you.

### CODE REVIEW

**Comment by holatuwol** [comment]
Why do you want to fix it by not escaping the HTML, but still leave in escaping the `title` attribute value?

**Comment by hongvo2308** [comment]
I have changed the HTML and see the expected result so I decided to do that. And, I am not sure about the role of the title in a tag so I am kind of afraid of changing it.

**Comment by hongvo2308** [comment]
Hi @holatuwol 
I have updated this PR. Please review it again and leave your comments.
Thank you.

**Comment by holatuwol** [comment]
Do you know if the problem manifests in vertical cards? The same pattern is present there.

https://github.com/holatuwol/liferay-portal/blob/debug-prompt-wcm-dm-folder-name/modules/apps/foundation/frontend-taglib/frontend-taglib/src/main/resources/META-INF/resources/card/vertical_card/end.jspf#L34-L38

**Comment by hongvo2308** [comment]
Hi @holatuwol 
I have updated this PR. I have changed the solution. Please review it again and leave your comments.
Thank you.

**Comment by hongvo2308** [comment]
> Do you know if the problem manifests in vertical cards? The same pattern is present there.
> 
> https://github.com/holatuwol/liferay-portal/blob/debug-prompt-wcm-dm-folder-name/modules/apps/foundation/frontend-taglib/frontend-taglib/src/main/resources/META-INF/resources/card/vertical_card/end.jspf#L34-L38

Thank you for pointing this out. This is really a good aspect.

**Comment by holatuwol** [comment]
Looking through the source code, there seem to be other uses of `HtmlUtil.escape()` in other portlets that use horizontal-card, such as wiki. Can you double-check whether these are affected by a similar bug?

**Comment by hongvo2308** [comment]
Hi @holatuwol 
I have updated this PR. I have added the fix for the similar bugs. Please review it again and leave your comments.
Thank you.

**Comment by holatuwol** [comment]
The fix itself looks fine.

The purpose of this prompt is to get you comfortable manually testing your changes when they affect many different areas of the portal. Since this touches so many different WCM and collaboration areas, the hope is that after this fix, you know how to access each of the different UI elements that you updated, because you took the time to check each of those UI elements.

This prompt was based on [LPS-70409](https://issues.liferay.com/browse/LPS-70409), so you're more than welcome to review the ticket (and any of its linked tickets) for additional context on the bug you were fixing.

**Pull request closed without merging**
