### PR TITLE
Lps 120487

### PR DESCRIPTION
**Pull request by hongvo2308**
This one passed my review. The original PR https://github.com/hongvo2308/liferay-portal/pull/4.
The ticket: https://issues.liferay.com/browse/LPP-38740

### CODE REVIEW

**Comment by holatuwol** [comment]
Making sure, this new check also takes into account the old check, `layout.isTypeAssetDisplay()`?

**Comment by hongvo2308** [comment]
Hi @holatuwol 
I have not looked into this aspect. I will ask @binhtran92 about this.
Thank you.

**Comment by binhtran92** [comment]
I'm not sure my understanding about this is correct, here is what I found:
`manifest.xml` mainly just contains the configuration for site-portlet. So that there is some portlet user add from the menu on the right that cannot find their configuration from there.

The old logic `layout.isTypeAssetDisplay()` was introduced by the ticket [LPS-106070](https://issues.liferay.com/browse/LPS-106070) to fixing the same issue as my ticket but in a different page template.

I think it is not about the layout type, the root cause is that the portlet cannot find it's configuration on the `ManifestSummary` then it losing configuration
[ExportImportHelperImpl.java#L1218-L1232](https://github.com/hongvo2308/liferay-portal/blob/LPS-120487/modules/apps/export-import/export-import-service/src/main/java/com/liferay/exportimport/internal/lar/ExportImportHelperImpl.java#L1218-L1232)

>In other words, is there any situation where layout.isTypeAssetDisplay() would have returned true, but the key exists in the manifest summary?
Yes, It could be the site-portlet.

**Comment by holatuwol** [comment]
@binhtran92 I see. I asked because I wanted to make sure we aren't introducing regressions with this change. Does your change still resolve [LPS-106070](https://issues.liferay.com/browse/LPS-106070)?

**Comment by binhtran92** [comment]
@holatuwol : yes, this PR also cover for ticket `LPS-106070`

**Comment by holatuwol** [comment]
https://github.com/vendeltoreki/liferay-portal/pull/121

**Pull request closed without merging**
