### PR TITLE
[TS] Prompt 2 -Web Content: Fix bug Asset Tag in Basic Web Content

### PR DESCRIPTION
**Pull request by haubuicodeengine**
@holatuwol Please help me review this PR

Test script
---------------------------
Steps to reproduce
1. Web Content > Add Basic Web Content
2. Copy and paste these tags into the Tags field (it contains upper-case letter and space):
"Redriven,carburized,abc      ,def        "
3. Press "enter" to add Tags
4. Publish Web Content. Successful publish.
5. Create another web content with the same tags.
6. Publish Web Content.

Result: Successful publish.

I will figure the "form-navigator" tag. It used to create basic web article templates. I find it quite complicated.

Thank you.

### CODE REVIEW

**Comment by holatuwol** [comment]
Why do you want to preserve case and leading/trailing spaces in tags?

**Comment by haubuicodeengine** [comment]
It is test data. We have 2 test cases:
- We keep uppercase, it's different from lowercase. It means there are 2 tags. Example: `Redriven` and `redriven`
- Asset tag content will be automatically trim before adding to the serviceContext.

**Comment by haubuicodeengine** [comment]
I'm wrong. In the document, they said

> Uppercase characters in tags aren’t recognized

I have updated the PR. Please help me to see and thank your material, @holatuwol .

**Comment by holatuwol** [comment]
No problem.

Sometimes, if we change what gets saved to the database, we need to check the official documentation (or check with the product team if such documentation is not available) to see if the current behavior is intended. This happened to be one of those cases.

If you'd like to understand more about the context, feel free to review [LPS-74630](https://issues.liferay.com/browse/LPS-74630) and its linked tickets.

**Pull request closed without merging**
