### PR TITLE
Lps 48290 -- Support for Malay language.

### PR DESCRIPTION
**Pull request by dhavaldesai75**
https://issues.liferay.com/browse/LPS-48290

Hi @holatuwol,

I have made the code change to add the language.ms=Malay in alphabetical order.
Please review it and provide feedback.

Thanks,

### CODE REVIEW

**Comment by holatuwol** [comment]
Can you squash the two commits together and have LPS-48290 be the first word in the squashed commit?

**Comment by dhavaldesai75** [comment]
I have squashed the two commits together. Please review. I followed the below steps.:
git rebase -i HEAD~2
git commit --amend to amend the commit message.
git push origin LPS-48290 --force.

**Comment by holatuwol** [comment]
@dhavaldesai75 : Since you added `/ms/c/portal/protected` as a path, can you add `/ms/*` as a servlet mapping?

**Comment by dhavaldesai75** [comment]
@holatuwol , added the servlet-mappings. Please review.

**Comment by dhavaldesai75** [comment]
Closing this as I have created another PR for LPS-48290-temp based on this branch.

**Pull request closed without merging**
