### PR TITLE
[TS] Prompt 2 - DM Folder Name: Remove escape text in Document and Media portlet

### PR DESCRIPTION
**Pull request by haubuicodeengine**
@holatuwol Please help me review this PR.

When i make changes in foundation/frontend-taglib, I'm not sure I can cover where the tag is used and I can't test all about it.

So I changed in the Document and Media portlet, Media Gallery portlet. And I found an error: No result with the keyword "&" in Documents and Media portlet.

Test script.
-------------------------------------------------------------------------------------------
Precondition: 

- Add the "&" folder and the "&" image into Document and Media Portlet.

Steps to check:

**Document and Media.**

- Check with Info, Icon, Descriptive, and List view.
- Delete, undo and check.

**Recycle Bin.**
- Delete all, go to Recycle Bin, and check with Info, Icon, Descriptive, and List view.

**Media Gallery.**
- Check view.
- Check text when hover and preview.

**Add all the portlets in Collaboration, Content Management group. Focus on some portlets below:**
- Most Viewed Assets.
- Asset Publisher.
- Highest Rated Assets.
- Recent Download.

If i miss some things, please let me know.
Thank you.

### CODE REVIEW

**Comment by holatuwol** [comment]
For this change:

https://github.com/holatuwol/liferay-portal/pull/122/commits/68192c884bbc5849b76a3412ce7c28804310d3b3#diff-e2fb34a0c4db3ad73cca610b02c90c58

Can you first confirm that this does not introduce a cross-site scripting vulnerability?

Additionally, looking through the source code, there seem to be other uses of `HtmlUtil.escape()` in other portlets, such as wiki. Can you double-check whether these are affected by a similar bug?

**Comment by haubuicodeengine** [comment]
Thank for your comment, @holatuwol .

Regarding changing from `title="<%= HtmlUtil.escapeAttribute(title) %>` 
to `title="<%= title %>`, "Title" attribute does not use for any other action, it is not active content. So i think it does not introduce a cross-site scripting vulnerability bug.

I tested in wiki portlet, knowledge base portlet and found the similar issue. I recognized the root cause is from the `liferay-frontend:horizontal-card` tag, we should not escape the html twice.

Please help me review it again.

And about why we should not escape twice, i don't understand too much.
I will analyze and answer you in next part of this prompt.

Thank you so much, @holatuwol .

**Comment by holatuwol** [comment]
*And about why we should not escape twice, i don't understand too much.*

Since this is intended to be a training exercise, can you investigate and provide an explanation for why it escapes twice?

**Comment by haubuicodeengine** [comment]
Sure. I tried it and found the reason was a scriptlet tag. It will output with an unescape value.
But I searched and found no official document on that.

Can you help me to get an idea on this, @holatuwol  ? 
Thank you so much.

**Comment by haubuicodeengine** [comment]
Sorry I was wrong. The scriptlet tag does not unescape value. It will make the original value. The html compiler reads(unescape) the content  and displays it on the page.

Is that correct ?
Thank you so much, @holatuwol .

**Comment by holatuwol** [comment]
Do you know how to navigate to look at the source code for tag libraries?

**Comment by haubuicodeengine** [comment]
Yes, we have a tld structure for defining attributes and tag class. From there, we can navigate to see the source code of the tag.

**Comment by holatuwol** [comment]
Have you checked the source code for the tag to see if the tag could be part of the problem?

**Comment by haubuicodeengine** [comment]
I just looked at the source code of the tag to know how it displayed and almost never doubt it. Thanks for your aspect.

**Comment by holatuwol** [comment]
Sure thing.

The only thing pending was your investigation into tag libraries to better understand the root cause, and your solution technically fixes the issue. I'll go ahead and close this pull request.

Please see [LPS-70409](https://issues.liferay.com/browse/LPS-70409) for additional context around the bug that you resolved with these changes.

**Pull request closed without merging**
