### PR TITLE
Lps 115949

### PR DESCRIPTION
**Pull request by hongvo2308**
[LPS-115949](https://issues.liferay.com/browse/LPS-115949)

### CODE REVIEW

**Comment by holatuwol** [comment]
Can you rename it to `max.memory` instead of `memory.threshold`?

**Comment by hongvo2308** [comment]
Hi @holatuwol 
I have updated this PR. Please be noted.
Thank you.

**Comment by holatuwol** [comment]
Why is it a `<=` check instead of an `==` check in the memory test?

**Comment by hongvo2308** [comment]
Hi @holatuwol 
Because I inspected that the memory which is fetched from the memoryMXBean.getHeapMemoryUsage().getMax() is about 99% ~ 85% of the memory value in the command. So I decide to use <= operator.

**Comment by holatuwol** [comment]
Ah, that makes sense, because we're not setting a minimum (-Xms). Can we add that as a setting, and then set it in the test?

**Comment by hongvo2308** [comment]
Shall I just set that argument in the Test only or also in the LocalProcessExecutor ?

**Comment by hongvo2308** [comment]
Actually, I have tried to add the -Xms arguments. But the result is 981 for the argument 1024. And 1963 for the argument 2048. I think that it holds a certain amount of memory for something else. So how do you think about this?

**Comment by holatuwol** [comment]
Looks like some of survivor space is excluded from the heap size, and you can't completely remove it (when I set NewSize and MaxNewSize to 0, there is still 0.5 MB allocated to something else).

https://plumbr.io/blog/memory-leaks/less-memory-than-xmx

Following that blog post, let's check the input arguments.

**Comment by hongvo2308** [comment]
Hi @holatuwol 
I have updated this PR. Using the -XX:+UseG1GC helps to return the exact memory. I used 8MB now since the 2MB does not work. Please review it again.
Thank you.

**Comment by holatuwol** [comment]
Can you change the method on ProcessConfig to `MaxMemory` instead of `MemoryThreshold`?

**Comment by hongvo2308** [comment]
Hi @holatuwol 
I have updated this PR. Please be noted.
Thank you.

**Comment by holatuwol** [comment]
https://github.com/ericyanLr/liferay-portal/pull/193

**Pull request closed without merging**
