### PR TITLE
Prompt2 - Fix Html escapse for folder name

### PR DESCRIPTION
**Pull request by huynguyen-codeengine**

### CODE REVIEW

**Comment by holatuwol** [comment]
There are other instances of `liferay-frontend:horizontal-card` in the portal that also have `HtmlUtil.escape` called in setting the `text` attribute.

Were you able to check to see if the bug also affects any of those other portlets?

**Comment by huynguyen-codeengine** [comment]
Have checked and found the bug affected on other portlet, fixed all the bugs I could reproduce then change the commit.

**Comment by holatuwol** [comment]
Can you explain why you updated the "title" attribute for the div in `document-library-web/src/main/resources/META-INF/resources/image_gallery_display/view_images.jsp`? It's not in any way similar to the other changes.

**Comment by huynguyen-codeengine** [comment]
I went through all `liferay-frontend:horizontal-card`  search results in the Liferay source code then add portlet to home page and try to reproduce bugs .  See the same bugs on the Media gallery portlet on image slide show, I decided to fix that bug as well by updating the "title" attribute.

**Comment by holatuwol** [comment]
Making sure, is `title` double-escaped in the HTML? I ask because if we were to update `dl.char.blacklist` in `portal-ext.properties` to allow quotes, this seems like it would introduce a cross-site scripting vulnerability.

**Comment by huynguyen-codeengine** [comment]
Have checked view_images.jsp:
String title = fileEntry.getTitle();
if (Validator.isNotNull(fileEntry.getDescription())) {
title += " - " + fileEntry.getDescription();
}
and fileEntry come from /document_library/cast_result.jspf:
fileEntry = DLAppLocalServiceUtil.getFileEntry(assetEntry.getClassPK()); has called
fileEntry = fileEntry.toEscapedModel();

I debugged deep down and found portal.kernel/bean/AutoEscapeBeanHandler.java has
result = HtmlUtil.escape((String)result); at line 70 -> the title has escape already.

**Comment by holatuwol** [comment]
Understood. It's possible that the issue with slide show still affects master, since the code change you suggested is not in place in master.

For additional context, please see [LPS-70409](https://issues.liferay.com/browse/LPS-70409).

**Pull request closed without merging**
