### PR TITLE
LPS-105583

### PR DESCRIPTION
**Pull request by hhtank**
https://issues.liferay.com/browse/LPS-105583

Please look at this fix again. Thanks!

### CODE REVIEW

**Comment by holatuwol** [comment]
This still has a similar issue.

1. Create a user with screen name `abc-`
2. Take note of the userId for the created user
3. Create a user with screen name `abc-{userId}`, where `{userId}` corresponds to the userId in step 2

**Comment by hhtank** [comment]
Hi @holatuwol 
Yep, i'm aware of the issue. But it sounds like not happen in real use cases. For the feature i'm working on, the implementation provided a fallback to avoid duplicate friendly URL automatically. As of what i see in core, there are cases that it create friendly URL automatically like `template-groupdId`, so the end user will not be able to use those.
I think there is no really correct way to fix this issue, then i'm trying to reduce the chance that the conflicts happen.
For other solutions, i can think of following:
1. By pass the validation at the time creating a user with duplicate screenname. Then the friendlyURL will be created without duplication. I'm not confident with this way, because it might lead to other issues in screenname or friendlyURL validation.
2. Keep the friendly URL exact as the screenname entered by user. This is also not really good, since it may have friendlyURL like `abc---..--------------`, if the user entered such value.

Could you give some hints in order to resolve this issue?
Thank you very much!

**Comment by holatuwol** [comment]
Can you send a pull request with option (1)?

**Comment by hhtank** [comment]
yeah, i'll have it pushed to this PR then. thanks!

**Comment by hhtank** [comment]
Hello @holatuwol 
This is my proposed fix which does not validate friendly URL while adding a new User, or the screenname unchanged.
Please see if this could be a solution that fixes the issue. I tested locally i it works as i expected.
Thanks,

**Comment by holatuwol** [comment]
https://github.com/jonathanmccann/liferay-portal/pull/1839

**Pull request closed without merging**
