### PR TITLE
LPS-71354

### PR DESCRIPTION
**Pull request by Ithildir**
Hi @holatuwol,
What do you think of this approach?

Thanks!

### CODE REVIEW

**Comment by holatuwol** [comment]
@Ithildir, I'm guessing that `my-subscriptions` is listed in the README because the inclusion/exclusion approach isn't able to deal with the `apps/collaboration/subscription/subscription-web` dependency on `:apps:my-subscriptions:my-subscriptions-web`?

This worries me, because if Liferay does anything like it in the future where we add something from a different root subfolder as a project dependency, we'd have to know to add the `my-subscriptions` equivalent at that time. That build failure is really puzzling unless you've spent a lot of time debugging Liferay's build dependencies.

**Comment by Ithildir** [comment]
Hi @holatuwol,
I think that dependency has been added by mistake, I already sent a pull to see if I'm right and it can be safely removed: https://github.com/sergiogonzalez/liferay-portal/pull/3869

**Comment by Ithildir** [comment]
Hi @holatuwol!
If this is okay and you think it's helpful, do you want me to send it to Brian?

Thanks!

**Comment by holatuwol** [comment]
@Ithildir Actually, looking at the other code that's already, could we add .lfrbuild-ci files for the folders that the CI needs and then delete the .lfrbuild-portal that we wouldn't include in a release? That way we wouldn't need another property and then everyone gets the benefit without even thinking about it.

**Comment by Ithildir** [comment]
@holatuwol, it's an option, yes. Not sure if there are any implications with the release tool but I can give it a try and see what Brian thinks about it!

**Comment by Ithildir** [comment]
@holatuwol, I checked, but there are other processes that use `.lfrbuild-portal`, for example the LPKG creation. Do you think it's a big problem to have that extra build property?

**Comment by Ithildir** [comment]
I sent it to Brian at https://github.com/brianchandotcom/liferay-portal/pull/47757. This could be a first step (I already had the `build.exclude.dirs` property anyway), we can keep thinking about it...

**Pull request closed without merging**
