### PR TITLE
Fixed the DM Folder Name WCM Collab Prompt.

### PR DESCRIPTION
**Pull request by dhavaldesai75**
Hi @holatuwol,

Please review the debug-prompt-wcm-dm-folder-name changes and provide feedback.

Thanks,
Dhaval

### CODE REVIEW

**Comment by holatuwol** [comment]
There are other instances of `liferay-frontend:horizontal-card` in the portal that also have `HtmlUtil.escape` called in setting the `text` attribute.

Were you able to check to see if the bug also affects any of those other portlets?

**Comment by holatuwol** [comment]
You also updated `liferay-frontend:add-menu-item` in `knowledge-base-web/src/main/resources/META-INF/resources/admin/add_button.jsp`.

Double-checking. Was it also affected by a similar bug?

**Comment by dhavaldesai75** [comment]
yes, It was affected by this type of bug. Attaching screen shot for your reference.
dm-folder-name-prompt-knowledge-article

**Comment by holatuwol** [comment]
Got it, thanks for the clarification!

Please see [LPS-70409](https://issues.liferay.com/browse/LPS-70409) for additional context around this issue.

**Pull request closed without merging**
