### PR TITLE
[TS][Prompt-5] Fix groupId and remove contentReviewerChecker logic

### PR DESCRIPTION
**Pull request by binhtran92**
Hi @holatuwol ,

I found that this bug related to MyWorklowTaskPortlet by the URL. Then I debug to see what happens here.
Firstly, I not quite understand what is `groupId`, then I go to database to check it and I found that it maybe the "site id". 
However `themeDisplay.getScopeGroupId()` return wrong `groupId` which is `control_panel` site not the site which has the portlet. So I fix it by get the real `groupId` from `workflowTask.optionalAttributes`.

From case 2: I saw that it will false at `permissionChecker.isContentReviewer()`. For me it not necessary, because the assignee of Workflow task could be by Role or User and following sentence already check it.
I also annotate at this condition to understand why the author write it at ticket [LPS-63813](https://issues.liferay.com/browse/LPS-63813). I test again with test case on this ticket and it still work well.
Because I cannot access to this ticket therefor I may not fully get the whole idea of this.

I'm not really confidence with this solution. Am I missing something? Please help me to review it.

BTW, I also run the format source code with:

```
ant setup-sdk compile
cd portal-impl
ant format-source-current-branch -Dgit.working.branch.name=0b366d695bacc6710d38e144d8fcfe94cd82fdb1
```

Thank you.

### CODE REVIEW

**Comment by holatuwol** [comment]
Before we can remove code, we need to understand what it was originally designed to do, so as to make sure we don't introduce a regression (where we break what that code was intended to fix).

In this case, the isContentReviewer check was added in order to address [LPS-63813](https://issues.liferay.com/browse/LPS-63813). Can you check to make sure your changes do not introduce a regression?

**Comment by binhtran92** [comment]
Base on the annotate, I found that the root cause for ticket [LPS-63813](https://issues.liferay.com/browse/LPS-63813) is that class `AssignTaskMVCActionCommand` didn't check the permission when assigning task.  The author fixed that by adding the condition and refactoring. I don't know why he force user when view the task has to be `contentReviewer`
I already check with the test case provided on ticket [LPS-63813](https://issues.liferay.com/browse/LPS-63813) and it still work fines. Because this condition is not the root cause to fix this ticket.

**Comment by holatuwol** [comment]
Got it. However, I'm still worried, because the commit message for ec89adf61b8eebfd19eb28565eee9d5e43710c4a (LPS-63813) reads, "Being content reviewer is necessary for, but not sufficient to, have permission to assign". The permission check you updated is also used when checking for assignment, not only for view, so it seems like it reverses the intent of the commit.

Can you fix the issue without removing those lines?

**Comment by binhtran92** [comment]
Hi @holatuwol,
I updated the PR, I decided to separate the `view` and `assign` permission checking. 
So that user don't have to become a `content reviewer` to view ticket that assign to them.
Please help me to review it.
Thank you.

**Comment by holatuwol** [comment]
Does this work if the user does not have one of the roles that can be assigned to the task?

**Comment by binhtran92** [comment]
Yes, becasue I just change the condition that will not return false when user want to view but isn't content reviewer. But these condition following will ensure that user have to have role that can be assigned to the task.
```
long[] roleIds = permissionChecker.getRoleIds(
			permissionChecker.getUserId(), groupId);

for (WorkflowTaskAssignee workflowTaskAssignee :
				workflowTask.getWorkflowTaskAssignees()) {

			if (isWorkflowTaskAssignableToRoles(
					workflowTaskAssignee, roleIds) ||
				isWorkflowTaskAssignableToUser(
					workflowTaskAssignee, permissionChecker.getUserId())) {

				return true;
			}
		}
```

**Comment by holatuwol** [comment]
What I mean is, can the user still access their task after you revoke their Site Administrator role?

**Comment by binhtran92** [comment]
There are 3 cases that user can access the task:
1. user have role 'Site Admin' or 'Content Reviewer'
2. user is owner of the task.
3. user have both role
So that in that prompt, 
+ test case 1: 
   - if we revoke the Site Administrator and Content Reviewer then user cannot access it.
+ test case: 2:
   - user can access their task because user is the owner no matter what they have role 'Site admin' or not. But when they want to assign the task, they has to have role.

**Comment by holatuwol** [comment]
Got it, compiled and confirmed test case 1. I don't have any additional questions.

For the original bug report, please see [LPS-66409](https://issues.liferay.com/browse/LPS-66409).

**Pull request closed without merging**
