### PR TITLE
[TS] Prompt 4 - Exposed Port : Port is not exposed.

### PR DESCRIPTION
**Pull request by haubuicodeengine**
@holatuwol Please help me review this PR.

Test script
--------------------------------------------------
Steps to Reproduce:
1. Set up apache
	I used docker: https://grow.liferay.com/share/Docker+Scripts
2. Set up Liferay to use Apache
	Set the portal-ext.properties to:
	web.server.http.port=80
	web.server.https.port=443
	web.server.protocol=https
	portal.proxy.path=/liferay
	redirect.url.ips.allowed=127.0.0.1,SERVER_IP,[the docker's IP]
	(Get the docker ip from ifconfig)
	Start Liferay and navigate to the homepage through [docker's IP]:8080
3. When the default landing page loads, right click anywhere on the page and select 'View Page Source'.
4. Search the page for "siteadminurl".

Result: 
The application server's port is not exposed.

------------------------------------------------
I do not have much knowledge about configuration and liferay. So with my understanding, I have 2 situations:
1. If `company.getVirtualhostname ()` returns the wrong value because I have a missing or wrong configuration setting. How do I set up the configuration correctly?
2. If `company.getVirtualhostname ()` returns the correct value, why are they different with the value ​​received from `themeDisplay`? What is the purpose of each one?

For me, I thought the first one might be right, and I tried, but failed.

Please give me your ideas or some instructions on this.

Thank you so much.

### CODE REVIEW

**Comment by holatuwol** [comment]
> 1. If `company.getVirtualhostname()` returns the wrong value because I have a missing or wrong configuration setting. How do I set up the configuration correctly?
> 2. If `company.getVirtualhostname()` returns the correct value, why are they different with the value ​​received from themeDisplay? What is the purpose of each one?

It's actually a database entry, so it's not aware of information that may come from the request. However, the value from `ThemeDisplay` comes from the request.

https://github.com/holatuwol/liferay-portal/blob/debug-prompt-core-server-port/portal-impl/src/com/liferay/portal/model/impl/CompanyImpl.java#L226-L248

> Please give me your ideas or some instructions on this.

When delivering fixes, we can't delete methods from the API, though we can add them. Changing a method signature is equivalent to deleting the old API and adding new API.

Would you be able to update your fix so that it doesn't delete any methods?

**Comment by haubuicodeengine** [comment]
I have updated the PR by adding new API with `ThemDisplay` parameter.

**Comment by holatuwol** [comment]
I believe the following line in your change will cause problems in the scenario when you're using HTTPS over AJP and not using any `web.server.protocol` properties.

```
sb.append(getPortalURL(serverName, getPortalServerPort(false), false));
```

Can you test a simple Apache HTTPd setup, connecting over AJP?

**Comment by holatuwol** [comment]
This solution looks good to me.

For additional context, please see [LPS-73587](https://issues.liferay.com/browse/LPS-73587).

**Pull request closed without merging**
