### PR TITLE
TSPrompt4-2 Fix the URL generated by PortalUtil

### PR DESCRIPTION
**Pull request by hongvo2308**
Hi @holatuwol ,
This is PR for Prompt4 Section2. I hope that you could review it and give me your comments.
Thank you.

### CODE REVIEW

**Comment by holatuwol** [comment]
Does your change still work if we switch over to HTTPS?

It looks like your implementation hard-codes a parameter value passed to `getPortalServerPort`, so in my head, and I don't see how it could work.

https://github.com/holatuwol/liferay-portal/blob/38310db1cbd37e98459a172b8aa473ec501ae086/portal-impl/src/com/liferay/portal/util/PortalImpl.java#L4990-L4993

If it does work, can you provide an explanation for why?

**Comment by hongvo2308** [comment]
Hi @holatuwol 
It still works when we change to HTTPS. Because I have configured the Apache Server with the virtual host in port 443.
`
<VirtualHost *:443>
    ProxyPreserveHost On

    SSLEngine on
    SSLCertificateFile "/usr/local/apache2/conf/dummy-server.crt"
    SSLCertificateKeyFile "/usr/local/apache2/conf/dummy-server.key"

    RequestHeader set X-Forwarded-Proto https
    
    ProxyPass /liferay http://192.168.1.5:8080
    ProxyPassReverse /liferay http://192.168.1.5:8080
</VirtualHost>
`
I guess I have misunderstood the prompt description. So could you please give me more details on this?
Thank you.

**Comment by holatuwol** [comment]
@hongvo2308 : As part of the review process, I want to make sure there's no regressions.

What if you switch it from an HTTP proxy to an AJP proxy?

**Comment by hongvo2308** [comment]
Hi @holatuwol 
I have not tried that yet. I will try it and give you the results later.

**Comment by hongvo2308** [comment]
Hi @holatuwol 
This solution still works. With the configuration to use the ajp protocol from the apache.
This is how I configure my apache https:
<VirtualHost *:443>
    ProxyPreserveHost On

    SSLEngine on
    SSLCertificateFile "/usr/local/apache2/conf/dummy-server.crt"
    SSLCertificateKeyFile "/usr/local/apache2/conf/dummy-server.key"

    # Default Option: Use http protocol
    RequestHeader set X-Forwarded-Proto https
    
    #ProxyPass /liferay http://192.168.1.5:8080
    #ProxyPassReverse /liferay http://192.168.1.5:8080

    # Option: Use ajp protocol
    ProxyPass /liferay ajp://192.168.1.6:8009
    ProxyPassReverse /liferay ajp://192.168.1.6:8009
</VirtualHost>

<VirtualHost *:8080>
    ProxyPreserveHost On

    #ProxyPass /liferay http://192.168.1.5:8080
    #ProxyPassReverse /liferay http://192.168.1.5:8080

    ProxyPass /liferay ajp://192.168.1.6:8009
    ProxyPassReverse /liferay ajp://192.168.1.6:8009
</VirtualHost>

**Comment by holatuwol** [comment]
I tested, and the solution doesn't work.

1. Start up a portal with your changes
2. Navigate to http://localhost:8080/
3. Navigate to https://localhost/
4. Open your browser console and run the following script:

```
Liferay.ThemeDisplay.getSiteAdminURL()
```

* Expectation is that it should read https://localhost/
* Actual behavior is that it reads http://localhost:8080/

**Comment by hongvo2308** [comment]
Hi @holatuwol 
Thank you for pointing this out. I will work on this.

**Comment by hongvo2308** [comment]
Hi @holatuwol 
I have updated this PR. Please be noted.
Thank you for your help.

**Comment by holatuwol** [comment]
Failed source formatting.

```
ant setup-sdk
cd portal-impl
ant format-source-current-branch -Dgit.working.branch.name=f5c5b70fbf2cdc82c30ac9e0935271ca78ef7c4b
```

**Comment by hongvo2308** [comment]
Hi @holatuwol 
Yes, I have updated this PR with the Source Formatting.

**Comment by holatuwol** [comment]
Looks okay now.

For additional context, please see [LPS-73587](https://issues.liferay.com/browse/LPS-73587).

**Pull request closed without merging**
