### PR TITLE
TS Prompt 2 - DM Folder Name WCM Collab

### PR DESCRIPTION
**Pull request by vsingleton**
Do not escape text for horizontal-card

### CODE REVIEW

**Comment by holatuwol** [comment]
Failed source formatting (trailing new lines at the end of the file).

```
ant setup-sdk
cd portal-impl
ant format-source-current-branch -Dgit.working.branch.name=4744a02f60d3604bdbadef54b8f9e31c17ff9bb7
```

**Comment by vsingleton** [comment]
The files that were changed were in modules/apps ... so instead of "ant format-source-current-branch" wouldn't it be something more like:

$ cd modules/apps
$ ../../gradlew formatSource

**Comment by holatuwol** [comment]
`ant format-source-current-branch` also runs source formatter for any updated modules.

You could run `gradlew formatSource` for specific modules, if only one or two modules changed, but whenever multiple modules change, I think it's easier to remember to run `ant format-source-current-branch` from `portal-impl`.

**Comment by vsingleton** [comment]
Makes sense.  Ok, this PR has been run through the source formatter and updated.

**Comment by holatuwol** [comment]
Assuming you didn't have any issues testing the changes, I don't see any issues with this pull request, and I would have forwarded it.

For additional context, please see [LPS-70409](https://issues.liferay.com/browse/LPS-70409).

**Pull request closed without merging**
