### PR TITLE
LPP-42324 - Custom meta tags is not saved after copying the page

### PR DESCRIPTION
**Pull request by huynguyen-codeengine**
Hi @holatuwol , 

   Please review this ticket from @thuycao-gs.

Thanks.

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by holatuwol** [comment]
It made more sense to me to delegate than to create a new private method.

Can you check to see if it still resolves the issue?

https://github.com/holatuwol/liferay-portal/commits/LPS-137263

**Comment by thuycao-gs** [comment]
Hi Mr. Minh Chau,
I have double-checked your update on this https://github.com/holatuwol/liferay-portal/commits/LPS-137263.

It resolved the issue for cases.
- Custom meta tags are saved after copying the page.
- Custom meta tags are saved after copying the page and publish the page.
- Update the custom meta tags on the child page but the parent page does not change and vice versa.
Thanks for your update.

**Comment by holatuwol** [comment]
https://github.com/liferay-echo/liferay-portal/pull/5682

**Pull request closed without merging**
