### PR TITLE
Lps 117986

### PR DESCRIPTION
**Pull request by hongvo2308**
[LPS-117986](https://issues.liferay.com/browse/LPS-117986)

### CODE REVIEW

**Comment by holatuwol** [comment]
Is there some way to do make this `@` somehow configurable from mentions-web, or to have the whole fix in mentions-web? I don't think I could convince the reviewer to add this code as it is.

**Comment by hongvo2308** [comment]
Hi @holatuwol 
I think it is defined here https://github.com/holatuwol/liferay-portal/blob/6168b2e4f1553e798dd93ea1b9c3989a0f08a362/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/autocomplete_input.js#L72. But I do not know how to reference to this class in *.js file. Do you have any suggestion?
Thank you.

**Comment by holatuwol** [comment]
If it's coming from `autocomplete_input.js`, that means it's all coming from ckeditor, so maybe if we make it more generally related to value (instead of hard-coding it to an `@` check), it could pass.

What is the value of `prevTriggerPosition.value` when it's not `@`? Is it just undefined?

**Comment by hongvo2308** [comment]
Hi @holatuwol 
I have updated this PR to use the condition `prevTriggerPosition.value`. Please be noted.
Thank you.

**Comment by holatuwol** [comment]
https://github.com/antonio-ortega/liferay-portal/pull/123

**Pull request closed without merging**
