### PR TITLE
[TS] Prompt2 DM Folder Name

### PR DESCRIPTION
**Pull request by dinh-thai**
Hi @holatuwol,
I have finish Prompt 2 DM Folder Name.
Beside that, I found 7 places more have using same HtmlUtil.escape() and I think should also fix them.

- /liferay-portal/modules/apps/collaboration/document-library/document-library-web/src/main/resources/META-INF/resources/image_gallery_display/view_images.jsp line 138

- /liferay-portal/modules/apps/collaboration/item-selector/item-selector-taglib/src/main/resources/META-INF/resources/group_selector/page.jsp line 68

-  /liferay-portal/modules/apps/collaboration/item-selector/item-selector-taglib/src/main/resources/META-INF/resources/repository_entry_browser/page.jsp line 318

- /liferay-portal/modules/apps/collaboration/wiki/wiki-web/src/main/resources/META-INF/resources/wiki/view.jsp line 381

- /liferay-portal/modules/apps/knowledge-base/knowledge-base-web/src/main/resources/META-INF/resources/admin/common/article_attachments.jsp line 44

- /liferay-portal/modules/apps/web-experience/journal/journal-web/src/main/resources/META-INF/resources/view_entries.jsp line 301

- /liferay-portal/modules/apps/web-experience/trash/trash-web/src/main/resources/META-INF/resources/view_content.jsp line 187

Please help me take a look.
Thanks you

### CODE REVIEW

**Comment by holatuwol** [comment]
> Beside that, I found 7 places more have using same HtmlUtil.escape() and I think should also fix them.

Were you able to reproduce the error in any of those 7 places?

**Comment by dinh-thai** [comment]
> Were you able to reproduce the error in any of those 7 places?

Hi @holatuwol 
After investigated and debugged, I found the bug will be occur when using tag `liferay-frontend:horizontal-card`and attribute `text`.
Beside that I also found the similar issue on image viewer and I also fix it on this branch.
So I would like to update the PR's content.

Please help me take a look.
Thanks you

**Comment by dinh-thai** [comment]
hi @holatuwol 
I have finish reproduced, investigated, debugged and fixed this prompt.
I think this prompt help me to learn how to reproduce and debugged. Look out for any related bug and reproduce all of that before fix, and check what happen after fix.
After fix it, I also run source code format:
```
ant setup-sdk compile
cd portal-impl
ant format-source-current-branch -Dgit.working.branch.name=bfc7ce5798d660247ed54668a8fa7e463371aa4a
```

Please help me take a look.
Thanks you

**Comment by holatuwol** [comment]
Can you explain why you updated the "title" attribute for the div in document-library-web/src/main/resources/META-INF/resources/image_gallery_display/view_images.jsp? It's not in any way similar to the other changes.

Can you explain why you used `bfc7ce5798d660247ed54668a8fa7e463371aa4a` as the base commit for source formatter?

**Comment by dinh-thai** [comment]
> Can you explain why you updated the "title" attribute for the div in `document-library-web/src/main/resources/META-INF/resources/image_gallery_display/view_images.jsp`? It's not in any way similar to the other changes.

Hi @holatuwol 
I update the "title" attribute because I see it have similar error.

This is code:
`<div class="image-link preview" <%= (hasAudio || hasVideo) ? "data-options=\"height=" + playerHeight + "&thumbnailURL=" + HtmlUtil.escapeURL(DLUtil.getPreviewURL(fileEntry, fileVersion, themeDisplay, "&videoThumbnail=1")) + "&width=640" + dataOptions + "\"" : StringPool.BLANK %> href="<%= imageURL %>" thumbnailId="<%= thumbnailId %>" title="<%= HtmlUtil.escapeAttribute(title) %>">`

This is UI:
image

Beside that, the caption of image viewer is assigned from title (at /liferay-portal/modules/apps/foundation/frontend-js/frontend-js-web/src/main/resources/META-INF/resources/liferay/item_viewer.js)
```
var caption = link.attr('title') || link.attr('data-title');
instance._captionEl.set('text', caption);
```
UI will:
image





> Can you explain why you used `bfc7ce5798d660247ed54668a8fa7e463371aa4a` as the base commit for source formatter?

I use command git rev-parse HEAD to get SHA1 hashes of HEAD and it return bfc7ce5798d660247ed54668a8fa7e463371aa4a, so I use it as the base commit for source formatter.

Please tell me more detail if I have any wrong steps.
Thank you!

**Comment by dinh-thai** [comment]
Hi @holatuwol 

I have run source code format again and it ok

image

Please help me review it.
Thank you!

**Comment by holatuwol** [comment]
It looks like the image gallery issue still exists in master, so you're more than welcome to create an LPS ticket and submit a fix for it.

With that being said, the original issue is based on [LPS-70409](https://issues.liferay.com/browse/LPS-70409), so please feel free to view the ticket and its linked issues for additional context.

**Pull request closed without merging**
