### PR TITLE
[TS] Prompt 4 - Calendar Permission : Fix Calendar Permission

### PR DESCRIPTION
**Pull request by haubuicodeengine**
@holatuwol Please help me review this PR

Test script
-------------------------------
Steps to reproduce:

1.- Add the calendar portlet to a page.
2.- Create a new Resource by going to the Resource tab and clicking "Add Resource" and naming it "My New Resource" and saving.
3.- Create a new regular user through the Control Panel and add them to the Liferay site under Edit User > Sites.
4.- From the Users and Organization menu, impersonate the regular user on another tab and ensure that the new calendar is shown on the calendar portlet, otherwise repeat step 2 as the regular user so that it appears.
5. In the impersonate tab, add the calendar related to that resource on the section "Other calendars" by typing "My New Resource".
6. As admin on the Calendar tab, add the calendar related to that resource on the section "Other calendars" by typing "My New Resource".
7.- As admin on the Calendar portlet, click on the "My New Resource" calendar arrow, and remove permissions on that calendar to everyone except to owner.
8.- On the other tab impersonating the regular user, revisit the page where the calendar is.

Result:  The "My New Resource" calendar is not shown.

------------------------
I fixed it by changing from `check` to` containts` method in the `CalendarServiceImpl` file. It will not throw exceptions.
In my opinion, it seems not right. I think we should fix when it collects the `calendarIds` list, makes it get the correct data, before they loop and fetch by calendarId.

Beside it,  i want to take some time to investigate `Liferay.CalendarList` component. I do not understand how it works.

Can you give me some ideas about that?
Thank you so much.

### CODE REVIEW

**Comment by holatuwol** [comment]
> I fixed it by changing from check to containts method in the CalendarServiceImpl file. It will not throw exceptions. In my opinion, it seems not right. 

I agree. This fix would be considered an API breaking change.

> I think we should fix when it collects the calendarIds list, makes it get the correct data, before they loop and fetch by calendarId.

I think that makes more sense as well.

> Beside it, i want to take some time to investigate Liferay.CalendarList component. I do not understand how it works.

So to make sure I understand, you've looked through [calendar_list.js](https://github.com/holatuwol/liferay-portal/blob/debug-prompt-core-permission/modules/apps/forms-and-workflow/calendar/calendar-web/src/main/resources/META-INF/resources/js/calendar_list.js) but the code is unclear?

**Comment by haubuicodeengine** [comment]
> So to make sure I understand, you've looked through calendar_list.js but the code is unclear?

Not yet. I just went to where to use "Liferay.store" and found that component.

Thank you so much,
I will fix and update this PR.

**Comment by haubuicodeengine** [comment]
@holatuwol Please help me review this PR.

I looked `calendar_list.js` to try to understand the `calendar` component a bit. It constructs a `calendar` component with properties and methods by Alloy. It is used to create `myCalendar`, `siteCalendar` and `otherCalendar`.

The Portlet fetches `calendarIds` values ​​by the current user. I think it's okay. So I fixed it by adding the `try ... catch` block in the `CalendarDisplayContext` file.

Thank you so much.

**Comment by holatuwol** [comment]
Failed source formatting.

```
ant setup-sdk
cd portal-impl
ant format-source -Dgit.working.branch.name=6257a36488d54790b9221d5b88077ffe9b65b9c2
```

**Comment by haubuicodeengine** [comment]
I updated this PR. Please help me review it.

**Comment by holatuwol** [comment]
> It has a warning format. It says that we should not catch PrincipalException or PortalException.

Can you provide the complete error message?

I don't see that error when I run it locally, and there are many examples where Liferay catches PrincipalException.

https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portlet/exportimport/service/impl/StagingLocalServiceImpl.java#L783-L797

**Comment by haubuicodeengine** [comment]
Sorry for my mistake. It says that is we should catch a portal/system exception, without any processing logic, just swallow it.

> [java] Unprocessed exception 'PrincipalException', see LPS-36174: ./modules/apps/forms-and-workflow/calendar/calendar-web/src/main/java/com/liferay/calendar/web/internal/display/context/CalendarDisplayContext.java 58

**Comment by holatuwol** [comment]
Ah, when it says "swallow an exception", it refers to not using the variable in the catch block. To resolve it, you can add the exception as a second parameter to `_log.info`.

**Comment by haubuicodeengine** [comment]
I have updated this PR. No warning appears. Thank you @holatuwol

**Comment by holatuwol** [comment]
Thanks! The changes make sense to me.

For additional context, please see [LPS-71251](https://issues.liferay.com/browse/LPS-71251).

**Pull request closed without merging**
