### PR TITLE
[TS] LPP-48297 > LPS-178212

### PR DESCRIPTION
**Pull request by tototrinh**
Hi @holatuwol,
Please help review this PR and leave your comments.
Tickets:
https://issues.liferay.com/browse/LPP-48297
https://issues.liferay.com/browse/LPS-178212
Previous PR:
https://github.com/brianchandotcom/liferay-portal/pull/132893

Notes:
I also received a comment from the Product team that 
"_It makes sense to utilize ServiceContext because that object is frontend related and so is the reason for adding the searchDescription parameter._ ". However, I was still concerned about whether serviceContext would need to be declared in this case and I also figured out that using LinkedHashMap can also work.
Regards.

### CODE REVIEW

**Comment by holatuwol** [comment]
* Can you fetch the thread local service context and call fetch `getAttributes` on it instead of forcing a new parameter?
* Can you default the behavior to true on both if no service context is available?

**Comment by tototrinh** [comment]
ci:test:bundle

**Comment by tototrinh** [comment]
ci:stop

**Comment by tototrinh** [comment]
ci:test:bundle

**Comment by tototrinh** [comment]
Hi @holatuwol, I update the code, please help take a look again. Thanks.
Notes:
- Using ServiceContextThreadLocal.getServiceContext() directly in *ServiceImpl as per the example in
https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/service/impl/UserLocalServiceImpl.java#L4872-L4873

**Comment by tototrinh** [comment]
ci:test:bundle

**Comment by tototrinh** [comment]
ci:test:bundle

**Pull request closed without merging**
