### PR TITLE
TSPrompt3-2 Remove the wrong condition logic

### PR DESCRIPTION
**Pull request by hongvo2308**
Hi @holatuwol 
I have made this PR for the Prompt 3 section 2. I hope that you could review it and give me your comments.
Thank you.

### CODE REVIEW

**Comment by holatuwol** [comment]
@hongvo2308 

I have two questions.

1. Can you explain why the current logic is wrong?
2. At the same time, can you update your pull request to make sure that there's no unnecessary checks? In your current else condition, there's never a situation where `hasExpired` will be true (because you simplified the if).

**Comment by hongvo2308** [comment]
Hi @holatuwol ,
1. The current logic is wrong because the statement `var sessionState = instance.get('sessionState');` just get the browser tab attribute. But we should get the cookies attribute like the way the timeStamp is got. So the sessionState will be inconsistent.
2. Yes, I will update the condition checks.

**Comment by hongvo2308** [comment]
Hi @holatuwol 
I have updated this PR. Please be noted.
Thank you.

**Comment by holatuwol** [comment]
In your latest changes, why did you remove `hasWarned` as well?

**Comment by hongvo2308** [comment]
> In your latest changes, why did you remove `hasWarned` as well?

It is in the parent if block already. So I think I can remove it.

**Comment by holatuwol** [comment]
Got it, that makes sense to me.

You mentioned that the reason the code is wrong is because it's not checking the cookie the way it does for the timestamp. I don't see any changes related to that.

Given that, how do your changes resolve the issue?

**Comment by hongvo2308** [comment]
> Got it, that makes sense to me.
> 
> You mentioned that the reason the code is wrong is because it's not checking the cookie the way it does for the timestamp. I don't see any changes related to that.
> 
> Given that, how do your changes resolve the issue?

Yes, The timeStamp is enough for updating the session state information. The extra condition form sessionState is not updated as the timeStamp. So it makes things go wrong. Therefore, I removed it.

**Comment by holatuwol** [comment]
Tested your changes and they resolve the issue!

For additional context around the original issue, please see [LPS-73444](https://issues.liferay.com/browse/LPS-73444).

**Pull request closed without merging**
