### PR TITLE
LPS-106268

### PR DESCRIPTION
**Pull request by hhtank**
https://issues.liferay.com/browse/LPS-106268

For this issue, i think just simply revert the commit which causes the bug is enough.

### CODE REVIEW

**Comment by holatuwol** [comment]
@hhtank : We aren't allowed to delete methods in order to resolve a bug.

**Comment by holatuwol** [comment]
Instead of reverting the commit, can you instead clean up the request attributes?

**Comment by hhtank** [comment]
> Instead of reverting the commit, can you instead clean up the request attributes?

Did you mean cleaning up after rendering the portlet? Or after doing transform the content... Let me take a look. But i doubt cleaning up `JavaConstants.JAVAX_PORTLET_RESPONSE` could be risky though.

**Comment by holatuwol** [comment]
@hhtank : Before transforming the content, we should remember what the request attributes were, and then after transforming the content, we should restore the original attribute values.

**Comment by holatuwol** [comment]
If that doesn't make sense, you can do a partial revert, retaining the API methods, and then double-check to make sure that LPS-92252 is no longer reproducible.

**Comment by hhtank** [comment]
> @hhtank : Before transforming the content, we should remember what the request attributes were, and then after transforming the content, we should restore the original attribute values.

Yeah, that is what i was switching to. Today i'm off so that i won't test it out until tomorrow.

**Comment by holatuwol** [comment]
https://github.com/jkappler/liferay-portal/pull/650

**Pull request closed without merging**
