### PR TITLE
LPP-37582: Create Manage layout for Organization

### PR DESCRIPTION
**Pull request by tototrinh**
Hi Minh Chau,
I updated my works for this ticket: https://issues.liferay.com/browse/LPP-37582.
In my way, I created a logic to generate a **"manage"** layout when creating an organization site.

Because I want to create a layout even without setting a template for Private Pages or Public Pages, I cannot set attribute **system_** to **false** => It could not be found by `getlayouts()` with _groupId_, _prarentLayoutId_ and _isPrivateLayout_  to be deleted in:
https://github.com/liferay/liferay-portal-ee/blob/master/portal-impl/src/com/liferay/portal/service/impl/LayoutLocalServiceImpl.java#L1069-L1072
https://github.com/liferay/liferay-portal-ee/blob/master/portal-impl/src/com/liferay/portal/service/persistence/impl/LayoutPersistenceImpl.java#L9300-L9415
Therefore, I added some code to ensure the layout will be removed when deleting an organization, although I think it is not a good choice.

Please help me review it and give me your feedback.
Thanks

### CODE REVIEW

**Comment by holatuwol** [comment]
Does this only help for new organizations, or does it work for existing organizations?

**Comment by holatuwol** [comment]
Can you check whether that the itemsURL here contains /group/org1/manage when the page does not yet exist, and if so, can you look into why it creates the /group/org1/manage URL?

https://github.com/liferay/liferay-portal/blob/master/modules/apps/product-navigation/product-navigation-taglib/src/main/resources/META-INF/resources/personal_menu/page.jsp#L85-L89

**Comment by tototrinh** [comment]
It's my fault, currently my solution it just works with a new organization.
I found that It will create item URL that contains /group/org1/manage/ if we're accessing org1 site with friendly URL is /group/org1/manage/. It will call `preloadItems` function when we focus on Personal-menu-dropdown:
https://github.com/liferay/liferay-portal/blob/master/modules/apps/product-navigation/product-navigation-taglib/src/main/resources/META-INF/resources/personal_menu/js/PersonalMenu.es.js#L54-L58
Then RESOURCE_PHASE is called and the group will be the site group (in the case of org1 group):
https://github.com/liferay/liferay-portal/blob/master/modules/apps/product-navigation/product-navigation-personal-menu-api/src/main/java/com/liferay/product/navigation/personal/menu/util/PersonalApplicationURLUtil.java#L94-L125
And Layout is got or created by:
 https://github.com/liferay/liferay-portal/blob/master/modules/apps/product-navigation/product-navigation-personal-menu-api/src/main/java/com/liferay/product/navigation/personal/menu/util/PersonalApplicationURLUtil.java#L94-L125

**Comment by holatuwol** [comment]
Will have the customer update their customization instead of applying a fix.

**Pull request closed without merging**
