### PR TITLE
TSPromt2-2: Fix the max entries perpage

### PR DESCRIPTION
**Pull request by hongvo2308**
Hi @holatuwol 
This PR is for the second part of the Promt 2. I hope that you could review it and leave your comments.
Thank you.

### CODE REVIEW

**Comment by holatuwol** [comment]
I believe your changes would prevent anyone from manually changing the delta to anything above the default entries per page, which seems like a regression.

Can you test and confirm?

**Comment by hongvo2308** [comment]
Hi @holatuwol 
Yes, I confirm that these changes prevent anyone from manually changing the delta to anything above the default entries per page. That what I supposed to do. I thought that the maximum entries per page should be the limit for the delta.
So for this case, we should allow the user to change the delta to any value. Is it correct?

**Comment by holatuwol** [comment]
Correct. The maximum entries to display is intended to be a default value.

**Comment by hongvo2308** [comment]
Hi @holatuwol 
I have updated this PR. Now the user can set the delta higher the default delta. Please review it again and leave your comments.
Thank you.

**Comment by holatuwol** [comment]
Looks okay to me.

This prompt was based on [LPS-67332](https://issues.liferay.com/browse/LPS-67332), so you're more than welcome to review the ticket (and any of its linked tickets) for additional context on the bug you were fixing.

**Pull request closed without merging**
