### PR TITLE
LPS-116291: PortletResource only use in case PortletConfiguration for referencing the right portlet

### PR DESCRIPTION
**Pull request by haubuicodeengine**
@holatuwol, @binhtran92, @vsingleton
 I created the PR to start the discussion for this ticket's solution.

From @binhtran92

> I found that the `portletResource` was introduced because the `PortletConfiguration` is loaded from different porlet. So they need that param to get preferences from the right portlet, as said from ticket https://issues.liferay.com/browse/LPS-44445.
> 
> However, I think when doing the refactor dependency at ticket https://issues.liferay.com/browse/LPS-55833, the author may assume that the PortletConfiguration is on all plugins (Portal and Market) then he decided to remove the condition.
> 
> So, my solution is, only set the portletResource if the portlet is PortletConfiguration. If not, just leave it as it is like the time this param was introduced.

I tested this solution and it worked fine.
But I saw 2 commits liferay@42c5f1f and liferay@2670193 . The `PORTLET_CONFIGURATION` was using in many places. This commit only partially reverted the code. I am not sure if it will affect other features or not.

What do you think about this, @holatuwol  ? 

Regards,
Hau Bui

### CODE REVIEW

**Comment by holatuwol** [comment]
Can you confirm that all uses of `"portletResource"` when generating URLs all relate to the configuration portlet?

```
git ls-files | tr '\n' '\0' | xargs -0 grep -F 'setParameter("portletResource"'
```

**Comment by haubuicodeengine** [comment]
Here is the result `git ls-files | tr '\n' '\0' | xargs -0 grep -F 'setParameter("portletResource"'`
<pre>modules/apps/asset/asset-publisher-web/src/main/java/com/liferay/asset/publisher/web/internal/display/context/BaseItemSelectorViewDisplayContext.java:		portletURL.setParameter(&quot;portletResource&quot;, portletResource);
modules/apps/asset/asset-publisher-web/src/main/resources/META-INF/resources/configuration/scope.jsp:itemSelectorURL.setParameter(&quot;portletResource&quot;, assetPublisherDisplayContext.getPortletResource());
modules/apps/asset/asset-publisher-web/src/main/resources/META-INF/resources/select_structure_field.jsp:portletURL.setParameter(&quot;portletResource&quot;, portletResource);
modules/apps/asset/asset-publisher-web/src/main/resources/META-INF/resources/view_asset_entries_abstract.jsp:						exportAssetURL.setParameter(&quot;portletResource&quot;, portletDisplay.getId());
modules/apps/asset/asset-publisher-web/src/main/resources/META-INF/resources/view_asset_entry_full_content.jsp:				exportAssetURL.setParameter(&quot;portletResource&quot;, portletDisplay.getId());
modules/apps/blogs/blogs-web/src/main/resources/META-INF/resources/blogs/entry_action.jsp:		editEntryURL.setParameter(&quot;portletResource&quot;, portletDisplay.getId());
modules/apps/blogs/blogs-web/src/main/resources/META-INF/resources/blogs/view_entry_content_detail.jsp:									editEntryURL.setParameter(&quot;portletResource&quot;, portletDisplay.getId());
modules/apps/blogs/blogs-web/src/main/resources/META-INF/resources/dynamic_include/portlet_header.jsp:		editEntryURL.setParameter(&quot;portletResource&quot;, portletDisplay.getId());
modules/apps/bookmarks/bookmarks-web/src/main/java/com/liferay/bookmarks/web/internal/portlet/toolbar/contributor/BookmarksPortletToolbarContributor.java:		portletURL.setParameter(&quot;portletResource&quot;, portletDisplay.getId());
modules/apps/bookmarks/bookmarks-web/src/main/java/com/liferay/bookmarks/web/internal/portlet/toolbar/contributor/BookmarksPortletToolbarContributor.java:		portletURL.setParameter(&quot;portletResource&quot;, portletDisplay.getId());
modules/apps/bookmarks/bookmarks-web/src/main/resources/META-INF/resources/bookmarks/entry_action.jsp:		editURL.setParameter(&quot;portletResource&quot;, portletDisplay.getId());
modules/apps/bookmarks/bookmarks-web/src/main/resources/META-INF/resources/bookmarks/folder_action.jsp:		editURL.setParameter(&quot;portletResource&quot;, portletDisplay.getId());
modules/apps/document-library/document-library-web/src/main/java/com/liferay/document/library/web/internal/display/context/FolderActionDisplayContext.java:		portletURL.setParameter(&quot;portletResource&quot;, portletDisplay.getId());
modules/apps/document-library/document-library-web/src/main/java/com/liferay/document/library/web/internal/display/context/logic/UIItemsBuilder.java:			portletURL.setParameter(&quot;portletResource&quot;, portletResource);
modules/apps/document-library/document-library-web/src/main/java/com/liferay/document/library/web/internal/portlet/toolbar/contributor/helper/MenuItemProvider.java:		portletURL.setParameter(&quot;portletResource&quot;, portletDisplay.getId());
modules/apps/document-library/document-library-web/src/main/java/com/liferay/document/library/web/internal/portlet/toolbar/contributor/helper/MenuItemProvider.java:		portletURL.setParameter(&quot;portletResource&quot;, portletDisplay.getId());
modules/apps/document-library/document-library-web/src/main/java/com/liferay/document/library/web/internal/portlet/toolbar/contributor/helper/MenuItemProvider.java:		portletURL.setParameter(&quot;portletResource&quot;, portletDisplay.getId());
modules/apps/export-import/export-import-changeset-taglib/src/main/resources/META-INF/resources/import_entity/page.jsp:	portletURL.setParameter(&quot;portletResource&quot;, ChangesetPortletKeys.CHANGESET);
modules/apps/export-import/export-import-web/src/main/resources/META-INF/resources/export_import.jsp:portletURL.setParameter(&quot;portletResource&quot;, portletResource);
modules/apps/export-import/export-import-web/src/main/resources/META-INF/resources/export_portlet.jsp:portletURL.setParameter(&quot;portletResource&quot;, portletResource);
modules/apps/export-import/export-import-web/src/main/resources/META-INF/resources/import_portlet.jsp:portletURL.setParameter(&quot;portletResource&quot;, portletResource);
modules/apps/export-import/export-import-web/src/main/resources/META-INF/resources/publish_portlet_navigation.jsp:portletURL.setParameter(&quot;portletResource&quot;, portletResource);
modules/apps/journal/journal-content-web/src/main/java/com/liferay/journal/content/web/internal/portlet/toolbar/contributor/JournalContentPortletToolbarContributor.java:		portletURL.setParameter(&quot;portletResource&quot;, portletDisplay.getId());
modules/apps/journal/journal-web/src/main/java/com/liferay/journal/web/internal/portlet/action/UpdateArticleMVCActionCommand.java:		portletURL.setParameter(&quot;portletResource&quot;, portletResource);
modules/apps/layout/layout-admin-web/src/main/java/com/liferay/layout/admin/web/internal/display/context/LayoutsAdminDisplayContext.java:		portletURL.setParameter(&quot;portletResource&quot;, getPortletResource());
modules/apps/layout/layout-admin-web/src/main/java/com/liferay/layout/admin/web/internal/portlet/action/BaseAddLayoutMVCActionCommand.java:		configureLayoutURL.setParameter(&quot;portletResource&quot;, portletResource);
modules/apps/layout/layout-content-page-editor-web/src/main/java/com/liferay/layout/content/page/editor/web/internal/portlet/configuration/icon/PortletPermissionsPortletConfigurationIcon.java:		portletURL.setParameter(&quot;portletResource&quot;, portletDisplay.getId());
modules/apps/plugins-admin/plugins-admin-web/src/main/resources/META-INF/resources/edit_plugin.jsp:												editURL.setParameter(&quot;portletResource&quot;, String.valueOf(portlet.getPortletId()));
modules/apps/plugins-admin/plugins-admin-web/src/main/resources/META-INF/resources/edit_plugin.jsp:												editURL.setParameter(&quot;portletResource&quot;, String.valueOf(portlet.getPortletId()));
modules/apps/portal-workflow/portal-workflow-task-web/src/main/java/com/liferay/portal/workflow/task/web/internal/display/context/WorkflowTaskDisplayContext.java:		editPortletURL.setParameter(&quot;portletResource&quot;, getPortletResource());
modules/apps/portlet-configuration/portlet-configuration-css-web/src/main/java/com/liferay/portlet/configuration/css/web/internal/portlet/configuration/icon/PortletConfigurationCSSPortletConfigurationIcon.java:			renderURL.setParameter(&quot;portletResource&quot;, portletDisplay.getId());
modules/apps/portlet-configuration/portlet-configuration-web/src/main/java/com/liferay/portlet/configuration/web/internal/display/context/PortletConfigurationPermissionsDisplayContext.java:		portletURL.setParameter(&quot;portletResource&quot;, _getPortletResource());
modules/apps/portlet-configuration/portlet-configuration-web/src/main/java/com/liferay/portlet/configuration/web/internal/display/context/PortletConfigurationPermissionsDisplayContext.java:		portletURL.setParameter(&quot;portletResource&quot;, _getPortletResource());
modules/apps/portlet-configuration/portlet-configuration-web/src/main/java/com/liferay/portlet/configuration/web/internal/display/context/PortletConfigurationTemplatesDisplayContext.java:		portletURL.setParameter(&quot;portletResource&quot;, getPortletResource());
modules/apps/portlet-configuration/portlet-configuration-web/src/main/java/com/liferay/portlet/configuration/web/internal/portlet/configuration/icon/ConfigurationTemplatesPortletConfigurationIcon.java:	portletURL.setParameter(&quot;portletResource&quot;, portletDisplay.getId());
modules/apps/portlet-configuration/portlet-configuration-web/src/main/java/com/liferay/portlet/configuration/web/internal/portlet/configuration/icon/PermissionsPortletConfigurationIcon.java:			portletURL.setParameter(&quot;portletResource&quot;, portletDisplay.getId());
modules/apps/portlet-configuration/portlet-configuration-web/src/main/resources/META-INF/resources/edit_public_render_parameters.jsp:editPublicRenderParameterURL.setParameter(&quot;portletResource&quot;, portletResource);
modules/apps/portlet-configuration/portlet-configuration-web/src/main/resources/META-INF/resources/edit_sharing.jsp:portletURL.setParameter(&quot;portletResource&quot;, portletResource);
modules/apps/roles/roles-admin-web/src/main/resources/META-INF/resources/edit_role_permissions_navigation.jspf:					editPermissionsResourceURL.setParameter(&quot;portletResource&quot;, usersAdminPortlet.getPortletId());
modules/apps/roles/roles-admin-web/src/main/resources/META-INF/resources/edit_role_permissions_navigation.jspf:					editPermissionsURL.setParameter(&quot;portletResource&quot;, usersAdminPortlet.getPortletId());
modules/apps/roles/roles-admin-web/src/main/resources/META-INF/resources/edit_role_permissions_navigation.jspf:					editPermissionsResourceURL.setParameter(&quot;portletResource&quot;, PortletKeys.PORTAL);
modules/apps/roles/roles-admin-web/src/main/resources/META-INF/resources/edit_role_permissions_navigation.jspf:					editPermissionsURL.setParameter(&quot;portletResource&quot;, PortletKeys.PORTAL);
modules/apps/roles/roles-admin-web/src/main/resources/META-INF/resources/edit_role_permissions_navigation.jspf:												editPermissionsResourceURL.setParameter(&quot;portletResource&quot;, panelAppPortlet.getPortletId());
modules/apps/roles/roles-admin-web/src/main/resources/META-INF/resources/edit_role_permissions_navigation.jspf:												editPermissionsURL.setParameter(&quot;portletResource&quot;, panelAppPortlet.getPortletId());
modules/apps/roles/roles-admin-web/src/main/resources/META-INF/resources/edit_role_permissions_navigation.jspf:												editPermissionsResourceURL.setParameter(&quot;portletResource&quot;, panelAppPortlet.getPortletId());
modules/apps/roles/roles-admin-web/src/main/resources/META-INF/resources/edit_role_permissions_navigation.jspf:												editPermissionsURL.setParameter(&quot;portletResource&quot;, panelAppPortlet.getPortletId());
modules/apps/roles/roles-admin-web/src/main/resources/META-INF/resources/edit_role_permissions_navigation.jspf:								editPermissionsResourceURL.setParameter(&quot;portletResource&quot;, panelAppPortlet.getPortletId());
modules/apps/roles/roles-admin-web/src/main/resources/META-INF/resources/edit_role_permissions_navigation.jspf:								editPermissionsURL.setParameter(&quot;portletResource&quot;, panelAppPortlet.getPortletId());
modules/apps/roles/roles-admin-web/src/main/resources/META-INF/resources/edit_role_permissions_navigation.jspf:										editPermissionsResourceURL.setParameter(&quot;portletResource&quot;, panelAppPortlet.getPortletId());
modules/apps/roles/roles-admin-web/src/main/resources/META-INF/resources/edit_role_permissions_navigation.jspf:										editPermissionsURL.setParameter(&quot;portletResource&quot;, panelAppPortlet.getPortletId());
modules/apps/roles/roles-admin-web/src/main/resources/META-INF/resources/edit_role_permissions_navigation.jspf:								editPermissionsResourceURL.setParameter(&quot;portletResource&quot;, curPortlet.getPortletId());
modules/apps/roles/roles-admin-web/src/main/resources/META-INF/resources/edit_role_permissions_navigation.jspf:								editPermissionsURL.setParameter(&quot;portletResource&quot;, curPortlet.getPortletId());
modules/apps/roles/roles-admin-web/src/main/resources/META-INF/resources/edit_role_permissions_navigation.jspf:							editPermissionsResourceURL.setParameter(&quot;portletResource&quot;, personalPortlet.getPortletId());
modules/apps/roles/roles-admin-web/src/main/resources/META-INF/resources/edit_role_permissions_navigation.jspf:							editPermissionsURL.setParameter(&quot;portletResource&quot;, personalPortlet.getPortletId());
modules/apps/roles/roles-admin-web/src/main/resources/META-INF/resources/edit_role_permissions_summary.jsp:	editPermissionsResourceURL.setParameter(&quot;portletResource&quot;, curPortletName);
modules/apps/roles/roles-admin-web/src/main/resources/META-INF/resources/edit_role_permissions_summary.jsp:	editPermissionsURL.setParameter(&quot;portletResource&quot;, curPortletName);
portal-web/docroot/html/portal/render_portlet.jsp:	urlConfiguration.setParameter(&quot;portletResource&quot;, portletDisplay.getId());
portal-web/docroot/html/portal/render_portlet.jsp:urlExportImport.setParameter(&quot;portletResource&quot;, portletDisplay.getId());
portal-web/docroot/html/portal/render_portlet.jsp:urlStaging.setParameter(&quot;portletResource&quot;, portletDisplay.getId());
util-taglib/src/com/liferay/taglib/portlet/ActionURLTag.java:			liferayPortletURL.setParameter(&quot;portletResource&quot;, portletResource);
util-taglib/src/com/liferay/taglib/security/PermissionsURLTag.java:		portletURL.setParameter(&quot;portletResource&quot;, portletDisplay.getId());
</pre>

**Comment by holatuwol** [comment]
@haubuicodeengine : Right, that's a list of the matches, but what we need to do before forwarding the pull request (based on the solution that you have right now) is to confirm that there are no regressions, so we need to manually check each of those results.

**Comment by binhtran92** [comment]
I have review many class related to `git ls-files | tr '\n' '\0' | xargs -0 grep -F 'setParameter("portletResource"'`. As I know currently `portletResource` using in many purpose. Mostly using for notify the message. Methods using for URL adding the `portletResource` is indicate that where this url come from.
Our solution, didn't touch this thing, because they get `portletResource` from url param, or portletId itself. We didn't manipulate the URL.

Our solution mainly related to features which are using the `portletDisplay` then I using `git ls-files | tr '\n' '\0' | xargs -0 grep -F 'portletDisplay.getPortletResource()`, I go through these classes and I can see all classes is related to the Configuration Portlet

**Comment by holatuwol** [comment]
https://github.com/dacousalr/liferay-portal/pull/266

**Pull request closed without merging**
