### PR TITLE
LPS-113477 Fix the recipient notification xml

### PR DESCRIPTION
**Pull request by haubuicodeengine**
@holatuwol Please help me review this PR ([LPS-113477](https://issues.liferay.com/browse/LPS-113477)). Thank you.

---------------------------------------
Steps to reproduce:
1. Sign in
2. Open Control Panel > Workflow > Single Approver > Edit
3. View source
4. Locate the "Creator Modification Notification"
5. Change the recipients to the following:
```
<recipients receptionType="to"> 
<user> 
<screen-name>test</screen-name> 
</user> 
</recipients> 
```
6. Click Update
7. Go back to the source and try to locate the Creator Modification Notification in the source code

Result:
The `screen-name` tag should not be replaced with the `user-id` tag.

### CODE REVIEW

**Comment by holatuwol** [comment]
@haubuicodeengine 

Reading through the code, it seems like there would only be one `userContent` value after iterating over all elements in the loop, which seems like a regression. Can you check what happens if you use the following value for the recipients before/after your changes?

```xml
<recipients receptionType="to"> 
<user>
<user-id>0</user-id>
<screen-name>test</screen-name> 
<email-address>test@liferay.com</email-address> 
</user> 
</recipients> 
```

If it fails to preserve all the values, can you check if the issue is resolved if you undo the source formatting commit https://github.com/liferay/liferay-portal/commit/fc0e0788c61baa6f94de96a6923c8c1be3d82389 (specifically, remove `filter(isValue)` and change the check back to `>`)?

**Comment by haubuicodeengine** [comment]
@holatuwol With recipient xml
```
<recipients receptionType="to"> 
<user>
<user-id>0</user-id>
<screen-name>test</screen-name> 
<email-address>test@liferay.com</email-address> 
</user> 
</recipients>
```

This is the result before my change, after my change and after i undo to the source formatting commit [liferay@fc0e078](https://github.com/liferay/liferay-portal/commit/fc0e0788c61baa6f94de96a6923c8c1be3d82389). They are same.
```
<recipients receptionType="to">
	<user>
		<user-id>0</user-id>
	</user>
</recipients>
```
--------------------------------
With 
```
<recipients receptionType="to"> 
<user>
<screen-name>test</screen-name> 
<email-address>test@liferay.com</email-address> 
</user> 
</recipients>
```

This is the result after i undo to the source formatting commit [liferay@fc0e078](https://github.com/liferay/liferay-portal/commit/fc0e0788c61baa6f94de96a6923c8c1be3d82389) and before i change

```
<recipients receptionType="to">
	<user/>
</recipients>
```
This is the result after my change
```
<recipients receptionType="to">
	<user>
		<email-address>test@liferay.com</email-address>
	</user>
</recipients>
```
I think the problem is that it only checks with the `if` clause based on `user-id` length.

**Comment by holatuwol** [comment]
What if you test master after stopping the kaleo designer bundle? Does it preserve all three, or are there elements that disappear afterwards?

**Comment by holatuwol** [comment]
If everything is preserved, can you test the behavior with the following code block?

```javascript
var xmlUser = XMLUtil.createObj('user');

buffer.push(xmlUser.open);

if (isArray(dataAssignments.userId)) {
	dataAssignments.userId.filter(isValue).forEach((item) => {
		buffer.push(XMLUtil.create('userId', item));
});

if (isArray(dataAssignments.emailAddress)) {
	dataAssignments.emailAddress.filter(isValue).forEach((item) => {
		buffer.push(XMLUtil.create('emailAddress', item));
	})
}

if (isArray(dataAssignments.screenName)) {
	dataAssignments.screenName.forEach((item) => {
		buffer.push(XMLUtil.create('screenName', item));
	})
}

buffer.push(xmlUser.close);
```

**Comment by haubuicodeengine** [comment]
With your code, inputs and outputs are the same, unchanged.
```
<recipients receptionType="to">
	<user>
		<user-id>0</user-id>
		<email-address>test@liferay.com</email-address>
		<screen-name>test</screen-name>
	</user>
</recipients>
```
You change the behavior when it serializes data. Instead of choosing one of the three elements, you keep it all. I think it will affect to the backend. Because this is the recipient's schema.
```
<xs:complexType name="user-complex-type">
	<xs:choice>
		<xs:element minOccurs="0" name="user-id" type="xs:long" />
		<xs:element minOccurs="0" name="screen-name" type="xs:string" />
		<xs:element minOccurs="0" name="email-address" type="email-address-type" />
	</xs:choice>
</xs:complexType>
```
Do you need me to check the effect in the backend if we keep all?

**Comment by holatuwol** [comment]
*Do you need me to check the effect in the backend if we keep all?*

No, but we do need to check what happens when Kaleo Designer doesn't exist.

**Comment by haubuicodeengine** [comment]
When Kaleo Designer doesn't exist, with the recipient xml
```
<recipients receptionType="to">
	<user>
		<user-id>0</user-id>
		<email-address>test@liferay.com</email-address>
		<screen-name>test</screen-name>
	</user>
</recipients>
```
After submitting the form, everything is preserved before and after I change.

**Comment by holatuwol** [comment]
In that case, I think we should proceed with a solution that preserves everything in Kaleo Designer as well. Can you update your commit with the changes?

**Comment by haubuicodeengine** [comment]
I have updated my commitment with the changes.
All elements will be preserved.

This is my test.
Input and output are same.

`<user/>`
```
<user>
	<email-address>test</email-address>
</user>
```
```
<user>
	<user-id></user-id>
	<screen-name>test</screen-name>
</user>
```
```
<user>
	<user-id></user-id>
	<screen-name>test</screen-name>
	<email-address>test@liferay.com</email-address>
</user>
```
```
<user>
	<user-id>0</user-id>
	<email-address>test@liferay.com</email-address>
	<screen-name>test</screen-name>
</user>
```
--------------------------------------------------
But when I press the "Save" button and move to Source tab
image
With input 
```
<user>
	<user-id>0</user-id>
	<email-address>test@liferay.com</email-address>
</user>
```
Output is 
```
<user>
	<user-id>0</user-id>
	<email-address>test@liferay.com</email-address>
	<screen-name></screen-name>
</user>
```

**Comment by holatuwol** [comment]
What's inside the `dataAssignments.screenName` in the last case, and why does `isValue` return true for those values?

**Comment by haubuicodeengine** [comment]
It is using [Lang.isValue](https://yuilibrary.com/yui/docs/api/classes/Lang.html#method_isValue). So it will return false for null/undefined/NaN, true for other values, including `0/false/''`

**Comment by haubuicodeengine** [comment]
What do you think if I add a function to check for empty strings ?

```
var isValidString = function (value) {
	if(isString(value) && value.trim().length > 0) {
		return true;
	}
	return false;
}
```

**Comment by holatuwol** [comment]
*What do you think if I add a function to check for empty strings?*

It looks like that function already exists, `isNotEmptyValue`. Can we update it to call `trim`, and use that existing function?

**Comment by haubuicodeengine** [comment]
I have updated the commitment. All elements will be preserved and all blank elements will be removed.

**Comment by holatuwol** [comment]
The product team picked up the ticket.

https://github.com/inacionery/liferay-portal/pull/665

**Pull request closed without merging**
