### PR TITLE
[TS][Prompt-2]DM-folder-name: Fix bug folder name was escaped

### PR DESCRIPTION
**Pull request by binhtran92**
Hi @holatuwol,
Please help me to review it.
Thanks

### CODE REVIEW

**Comment by holatuwol** [comment]
There are other instances of `liferay-frontend:horizontal-card` in the portal that also have `HtmlUtil.escape` called in setting the `text` attribute.

Were you able to check to see if the bug also affects any of those other portlets?

**Comment by binhtran92** [comment]
Hi @holatuwol ,
I updated the PR. On this prompt, I have learned about how to debug the frontend taglib and I found the root cause is that the folder name was escaped 2 times. Because on the taglib already have one for the `text` attribute then when we using this taglib we dont have to escape the title.
In addition, I also learn to reproduce all the cases that affected by the `<liferay-frontend:horizontal-card>`
By the way, I run the source format by `ant format-source-current-branch -Dgit.working.branch.name=5b611c4ca0adff668f87d9f9d3cc19f75e49dd85`. But seem like this cannot check the jsp or js stuffs.
Please help me to review it. 
Thank you.

**Comment by holatuwol** [comment]
Can you explain why you updated the "title" attribute for the div in `document-library-web/src/main/resources/META-INF/resources/image_gallery_display/view_images.jsp`? It's not in any way similar to the other changes.

**Comment by binhtran92** [comment]
> Can you explain why you updated the "title" attribute for the div in `document-library-web/src/main/resources/META-INF/resources/image_gallery_display/view_images.jsp`? It's not in any way similar to the other changes.

It related to [https://github.com/holatuwol/liferay-portal/blob/debug-prompt-wcm-dm-folder-name/modules/apps/foundation/frontend-js/frontend-js-web/src/main/resources/META-INF/resources/liferay/item_viewer.js](ItemViewer). As you can see at line 608, they using the attribute _title_ for the caption.

**Comment by holatuwol** [comment]
When `item_viewer.js` uses it, is it double-escaped?

**Comment by binhtran92** [comment]
Hi @holatuwol ,
I was wrong about HTML escaped it-self. However in this case, I found that on _view_images.jsp_ at line 86 
`String title = fileEntry.getTitle();`. The `title` already escaped because the `fileEntry` is extend from `DLFileEntryModel` which is anotated by `@AutoEscape` at method `getTitle()`. So that we don't have to escaped it.

**Comment by holatuwol** [comment]
It looks like the image gallery issue still exists in master, so you're more than welcome to create an LPS ticket and submit a fix for it.

With that being said, the original issue is based on [LPS-70409](https://issues.liferay.com/browse/LPS-70409), so please feel free to view the ticket and its linked issues for additional context.

**Pull request closed without merging**
