### PR TITLE
TSPrompt4-1 Adjust the fetch function not to throw error

### PR DESCRIPTION
**Pull request by hongvo2308**
Hi @holatuwol 
This is the PR for the Prompt4 Section1. I hope that you could review it and leave your comments.
Thank you.

### CODE REVIEW

**Comment by holatuwol** [comment]
While there is precedent for doing this in a method that doesn't return a list (`KBArticleServiceImpl`, for example), that started out this way. The method you're updating, on the other hand, has always thrown a `PrincipalException`.

Therefore, this fix would be considered an API breaking change, because the API method no longer throws a `PrincipalException` when failing a permission check, but instead just returns null. While you could argue that returning null is more secure, and thus an API change is necessary, you would need to support it by also updating all the other methods to behave the same way.

Can you instead attempt to address the issue without suppressing the `PrincipalException` from inside of the `CalendarService` implementation?

**Comment by hongvo2308** [comment]
Hi @holatuwol 
Yes, I will try to find an alternative solution.
Thank you.

**Comment by hongvo2308** [comment]
Hi @holatuwol 
I updated to use try-catch block at the CalendarDisplayContext. Please be noted.
Thank you.

**Comment by holatuwol** [comment]
This makes sense to me.

If you'd like to see additional context, please see [LPS-71251](https://issues.liferay.com/browse/LPS-71251). You can see the similarities in your original solution and the updated solution in the actual pull request that resolved the issue.

**Pull request closed without merging**
