### PR TITLE
[Prompt5] Workflow Permissions: Update groupId and permission check

### PR DESCRIPTION
**Pull request by dinh-thai**
Hi @holatuwol ,

After reproduce this issue, I used Eclipse for debugged.
When debugged, I see that the permission check base on group. The groupId is get from `themeDisplay.getScopeGroupId()`, it is not a id of `My Site` site, show it return the user is not have permission.
The solution is get groupId from `workflowTask.getOptionalAttributes()`.
Beside that, in method `com.liferay.portal.workflow.task.web.permission.WorkflowTaskPermissionChecker.hasPermission(long, WorkflowTask, PermissionChecker)`, the code changed from LPS-63813:
```
if (!permissionChecker.isContentReviewer(
		permissionChecker.getCompanyId(), groupId)) {

	return false;
}
```
is not enough condition. I have add a new method for check one more condition.
After change code, I run code format with working branch name and it show NullPointerException.
```
➜  portal-impl git:(debug-prompt-workflow) ✗ ant format-source-current-branch -Dgit.working.branch.name=9a77ccd48f794136904222b822201938866b6651
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
Buildfile: /home/ces-user/liferay-projects/liferay-portal/portal-impl/build.xml

format-source-current-branch:

format-source:
     [java] Loading file:/home/ces-user/liferay-projects/liferay-portal/portal-impl/classes/system.properties
     [java] Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.NullPointerException
     [java] 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
     [java] 	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
     [java] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:195)
     [java] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:136)
     [java] Caused by: java.lang.NullPointerException
     [java] 	at com.liferay.portal.kernel.io.unsync.UnsyncStringReader.<init>(UnsyncStringReader.java:34)
     [java] 	at com.liferay.source.formatter.BaseSourceProcessor.readXML(BaseSourceProcessor.java:2435)
     [java] 	at com.liferay.source.formatter.JSPSourceProcessor._populateTagJavaClasses(JSPSourceProcessor.java:1931)
     [java] 	at com.liferay.source.formatter.JSPSourceProcessor.preFormat(JSPSourceProcessor.java:1887)
     [java] 	at com.liferay.source.formatter.BaseSourceProcessor.format(BaseSourceProcessor.java:90)
     [java] 	at com.liferay.source.formatter.SourceFormatter._runSourceProcessor(SourceFormatter.java:249)
     [java] 	at com.liferay.source.formatter.SourceFormatter.access$000(SourceFormatter.java:40)
     [java] 	at com.liferay.source.formatter.SourceFormatter$1.call(SourceFormatter.java:181)
     [java] 	at com.liferay.source.formatter.SourceFormatter$1.call(SourceFormatter.java:177)
     [java] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     [java] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
     [java] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
     [java] 	at java.lang.Thread.run(Thread.java:748)
     [java] Java Result: 1

```
And when I run format with format-source-latest-author and it success.
```
➜  portal-impl git:(debug-prompt-workflow) ✗ ant format-source-latest-author 
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
Buildfile: /home/ces-user/liferay-projects/liferay-portal/portal-impl/build.xml

format-source-latest-author:

format-source:
     [java] Loading file:/home/ces-user/liferay-projects/liferay-portal/portal-impl/classes/system.properties
     [java] ./modules/apps/forms-and-workflow/portal-workflow/portal-workflow-task-web/src/main/java/com/liferay/portal/workflow/task/web/permission/WorkflowTaskPermissionChecker.java
     [java] ./modules/apps/forms-and-workflow/portal-workflow/portal-workflow-task-web/src/main/java/com/liferay/portal/workflow/task/web/portlet/action/AssignTaskMVCActionCommand.java
     [java] ./modules/apps/forms-and-workflow/portal-workflow/portal-workflow-task-web/src/main/java/com/liferay/portal/workflow/task/web/portlet/MyWorkflowTaskPortlet.java

BUILD SUCCESSFUL
Total time: 6 seconds

```
So I think maybe format-source-current-branch has any error.

Please help me review.
Thank you.

### CODE REVIEW

**Comment by holatuwol** [comment]
Wanted to double-check. Before the reviewer rejects it, does the task show up in My Workflow Tasks?

**Comment by holatuwol** [comment]
I compiled and tested, and the task doesn't show up in My Workflow Tasks.

**Comment by dinh-thai** [comment]
Hi @holatuwol ,
I am joining project of Australia's customer, so I will check this prompt after finish the project.
Thank you.

**Comment by holatuwol** [comment]
Closing due to inactivity.

**Pull request closed without merging**
