### PR TITLE
[Technical-support] Prompt4 - Calendar Permission : Adjust function fetchCalendar to avoid throwing errors

### PR DESCRIPTION
**Pull request by tototrinh**
I updated my work for this prompt. Please have a look and give me your comments. Thank you

### CODE REVIEW

**Comment by holatuwol** [comment]
While there is precedent for doing this in a method that doesn't return a list (`KBArticleServiceImpl`, for example), that started out this way. The method you're updating, on the other hand, has always thrown a `PrincipalException`.

Therefore, this fix would be considered an API breaking change, because the API method no longer throws a `PrincipalException` when failing a permission check, but instead just returns null. While you could argue that returning null is more secure, and thus an API change is necessary, you would need to support it by also updating all the other methods to behave the same way.

Can you instead attempt to address the issue without suppressing the `PrincipalException` from inside of the `CalendarService` implementation?

**Comment by tototrinh** [comment]
Hi @holatuwol 
Instead of returning null as I did before I used Try-catch block at CalendarDisplayContext  to resolve this prompt. Please take a look. Thanks

**Comment by holatuwol** [comment]
Failed source formatting.

```
ant setup-sdk
cd modules
../gradlew :apps:forms-and-workflow:calendar:calendar-web:formatSource
```

You can ignore the error about reaching out to SOLR to lookup the latest version (since that's a bug in the Gradle plugin used for checking for outdated versions of the plugin), but the source formatter reports a few errors related to your changes.

**Comment by tototrinh** [comment]
Thanks for letting me know about that. I will pay more attention to the source format.

**Comment by holatuwol** [comment]
It looks like it's still failing source formatter.

**Comment by tototrinh** [comment]
After checking again, I found that an error occurred during the formatting process that I had previously ignored: 
`java.io.IOException: Server returned HTTP response code: 400 for URL: https://search.maven.org/solrsearch/select?q=g:"com.liferay"+AND+a:"com.liferay.source.formatter"&wt=json
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
`
On the other hand, I also see messages that indicate where the format is corrupt.

**Comment by holatuwol** [comment]
You can ignore the HTTP response code 400 error, and focus on the code changes.

**Comment by tototrinh** [comment]
I updated my change for source format. Please have a look. Thanks.

**Comment by holatuwol** [comment]
It's still issuing a warning about this code block, because there is a line that's 82 characters, so you'll need to shorten the message or do some kind of string concatenation instead of using String.format.

```
				_log.error(
					String.format(
						"This user does not have VIEW permission for calendar %d",
						calendarId));
```

**Comment by tototrinh** [comment]
I made many mistakes in Source format. I really need to be more careful. I used "+" instead of String.format. I hope I made the right choice.

**Comment by holatuwol** [comment]
*I hope I made the right choice.*

Another option would have been to have the message say "User" instead of "This user" since that would remove 5 characters.

For more context, please see [LPS-71251](https://issues.liferay.com/browse/LPS-71251).

**Pull request closed without merging**
