### PR TITLE
[TECHNICAL-SUPPORT] LPS-99330 AssertionError in LayoutSetPrototypePropagationTest

### PR DESCRIPTION
**Pull request by vendeltoreki**
Hi @holatuwol ,

I think there was a typo in one of the commits in [LPS-95817](https://issues.liferay.com/browse/LPS-95817):
https://github.com/liferay/liferay-portal/commit/ee47ff329a6325fa075c2828b2a5a7831aa3aefb#diff-ebbebf62f0bf0ad69c9ad02ebef3d3d6R165 , that I did not notice during testing.

Please review this change.

Thanks,
Vendel

### CODE REVIEW

**Comment by vendeltoreki** [comment]
ci:test

**Comment by holatuwol** [comment]
Watching for `ci:test:staging` results on https://github.com/vendeltoreki/liferay-portal/pull/13

**Comment by holatuwol** [comment]
ci:test:sf

**Comment by holatuwol** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/76724

**Pull request closed without merging**
