### PR TITLE
TSPromt2-3 Preprocess the tag names before pass to service

### PR DESCRIPTION
**Pull request by hongvo2308**
Hi @holatuwol 
This is the PR for the third part of the Prompt 2. I hope that you could review it and leave your comments.
Thank you.

### CODE REVIEW

**Comment by holatuwol** [comment]
Failed source formatting.

```
ant setup-sdk
cd portal-impl
ant format-source-current-branch -Dgit.working.branch.name=53200f57e2eb7a8929f4b6030ccaffd672ec2441
```

**Comment by hongvo2308** [comment]
Hi @holatuwol 
I have updated the source format. Please review it again and leave your comments.
Thank you.

**Comment by holatuwol** [comment]
Double-checking, is journal the only portlet that has this issue?

**Comment by hongvo2308** [comment]
Hi @holatuwol 
I have changed the solution. I updated inside the AssetTagLocalServiceImpl instead. Please review it again and leave your comments.
Thank you.

**Comment by holatuwol** [comment]
That looks okay for me.

For context, this prompt is based on [LPS-74630](https://issues.liferay.com/browse/LPS-74630). Please feel free to review this older ticket and let me know if you have any additional questions.

**Pull request closed without merging**
