### PR TITLE
LPS-151510-2

### PR DESCRIPTION
**Pull request by ericyanLr**
Hi @holatuwol ,

Previous PR: https://github.com/holatuwol/liferay-portal/pull/258

Here is another approach to add support for HEIC images. This approach takes more into consideration, the original implementation of the ImageProcessor, where the previewType dictates the image type of the generated image file.

However, currently it's more expensive, since it has to determine the mime type of the generated file before saving. If this can be further optimized, that would be great. (I couldn't figure out an easy way to do this without introducing a major version bump)

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
ci:stop

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by holatuwol** [comment]
Between the two options, this one would be better because we can actually backport it (no major version bump).

Did you check if there were any useful property names on the RenderedImage?
* https://docs.oracle.com/javase/7/docs/api/java/awt/image/RenderedImage.html#getPropertyNames()

**Comment by ericyanLr** [comment]
By RenderedImage, are you referring to the renderedImage retrieved here: 
- https://github.com/holatuwol/liferay-portal/pull/259/files#diff-775acb94fac29b6c1fef3c11e085302c7c972b5eacc294f746fe87a3614d1421R84 

If so, I just tested it and unfortunately, it returns null.

**Comment by holatuwol** [comment]
https://github.com/liferay-lima/liferay-portal/pull/2977

**Pull request closed without merging**
