### PR TITLE
LPS-102368 In Calendar's monthly view, when today's date is the last week of the month, the blue border is cut out

### PR DESCRIPTION
**Pull request by knchau**
https://issues.liferay.com/browse/LPS-102368

AUI pr: https://github.com/holatuwol/alloy-ui/pull/3

Liferay interval is originally using the default number of days per interval, which works for demo because demo is using the defaults in their calendar view whereas Liferay's calendar display is meant to show only the minimum amount of weeks pertaining to each month. 

https://github.com/holatuwol/liferay-portal/commit/2eac9cb6bcf6279debfd916d750fdd3016bdd703: Instead of using default displayDaysInterval, we recalculate the interval for each month. 

https://github.com/holatuwol/liferay-portal/commit/716e3f944d4bcff9c2aabc6bb2d5e07c913ca13d: Calendar was choosing to hide table rows rather than readjust the table rows. Table rows are adjusted depending on the current size to the number of weeks. If there are more weeks than rows, a row would be added otherwise the rows would be left alone or removed.  

https://github.com/holatuwol/liferay-portal/commit/5792df8f5c1e5ea6e02b6f3f167370c9757bc1c3: The table row's container would then be repopulated.

### CODE REVIEW

**Comment by knchau** [comment]
ci:test:sf

**Comment by knchau** [comment]
ci:test:relevant

**Comment by knchau** [comment]
ci:test:sf

**Comment by knchau** [comment]
ci:test:relevant

**Comment by holatuwol** [comment]
https://github.com/knchau/liferay-portal/pull/8

**Pull request closed without merging**
